@echo off
cd /d "%~dp0"
start "" "%~dp0index.html"
start "" "%~dp0shop.html"
start "" "%~dp0product.html"
start "" "%~dp0category.html"
start "" "%~dp0cart.html"
start "" "%~dp0checkout.html"
start "" "%~dp0wishlist.html"
start "" "%~dp0account.html"
