<?php
/**
 * Legal-page UI translations embedded in the theme.
 *
 * @package Doroshopping
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Legal page packs (EN, DE, FR, IT and PT).
 *
 * @return array<string, array<string, string>>
 */
function doroshopping_i18n_builtin_ui_legal_packs() {
	$entries = array(
		'doroshopping_ui_legal_eyebrow' => array( 'Legal information', 'Rechtliche Informationen', 'Informations légales', 'Informazioni legali', 'Informação legal' ),
		'doroshopping_ui_legal_updated' => array( 'Last updated: %s', 'Letzte Aktualisierung: %s', 'Dernière mise à jour : %s', 'Ultimo aggiornamento: %s', 'Última atualização: %s' ),
		'doroshopping_ui_legal_toc_aria' => array( 'Page table of contents', 'Seitenübersicht', 'Sommaire de la page', 'Indice della pagina', 'Índice da página' ),
		'doroshopping_ui_legal_toc_title' => array( 'On this page', 'Auf dieser Seite', 'Sur cette page', 'In questa pagina', 'Nesta página' ),
		'doroshopping_ui_legal_related_aria' => array( 'Related pages', 'Verwandte Seiten', 'Pages associées', 'Pagine correlate', 'Páginas relacionadas' ),
		'doroshopping_ui_legal_related_title' => array( 'You may also be interested in', 'Das könnte Sie auch interessieren', 'Vous pourriez aussi être intéressé par', 'Potrebbero interessarti anche', 'Também poderá interessar-lhe' ),
		'doroshopping_ui_legal_footer_title' => array( 'Useful links', 'Nützliche Links', 'Liens utiles', 'Link utili', 'Ligações úteis' ),
		'doroshopping_ui_legal_unknown' => array( 'No specific legal content is available for this page.', 'Für diese Seite sind keine spezifischen rechtlichen Inhalte verfügbar.', 'Aucun contenu juridique spécifique n’est disponible pour cette page.', 'Non sono disponibili contenuti legali specifici per questa pagina.', 'Não existe conteúdo legal específico disponível para esta página.' ),
		'doroshopping_ui_cms_rel_payments' => array( 'Payment methods', 'Zahlungsmethoden', 'Modes de paiement', 'Metodi di pagamento', 'Métodos de pagamento' ),
		'doroshopping_ui_cms_rel_shipping' => array( 'Shipping', 'Versand', 'Livraison', 'Spedizioni', 'Envios' ),
		'doroshopping_ui_cms_rel_protect' => array( 'Buyer protection', 'Käuferschutz', 'Protection de l’acheteur', 'Protezione acquirente', 'Proteção do comprador' ),
		'doroshopping_ui_cms_rel_returns' => array( 'Returns', 'Rückgaben', 'Retours', 'Resi', 'Devoluções' ),
		'doroshopping_ui_cms_rel_terms' => array( 'Terms', 'Bedingungen', 'Conditions', 'Termini', 'Termos' ),
		'doroshopping_ui_cms_rel_legal' => array( 'Legal notice', 'Impressum', 'Mentions légales', 'Note legali', 'Aviso legal' ),
		'doroshopping_ui_cms_rel_cookies' => array( 'Cookies', 'Cookies', 'Cookies', 'Cookie', 'Cookies' ),
		'doroshopping_ui_cms_rel_privacy' => array( 'Privacy', 'Datenschutz', 'Confidentialité', 'Privacy', 'Privacidade' ),
		'doroshopping_ui_cms_rel_help' => array( 'Help centre', 'Hilfe-Center', 'Centre d’aide', 'Centro assistenza', 'Centro de ajuda' ),

		'doroshopping_ui_legal_privacy_intro' => array( 'This Privacy Policy explains how we process your personal data when you use our online store, in accordance with the GDPR (EU) 2016/679 and the LOPDGDD.', 'Diese Datenschutzerklärung erläutert, wie wir Ihre personenbezogenen Daten verarbeiten, wenn Sie unseren Onlineshop nutzen, gemäß DSGVO (EU) 2016/679 und LOPDGDD.', 'Cette politique de confidentialité décrit la manière dont nous traitons vos données personnelles lorsque vous utilisez notre boutique en ligne, conformément au RGPD (UE) 2016/679 et à la LOPDGDD.', 'La presente Informativa sulla privacy descrive come trattiamo i tuoi dati personali quando utilizzi il nostro negozio online, in conformità al RGPD (UE) 2016/679 e alla LOPDGDD.', 'Esta Política de Privacidade descreve como tratamos os seus dados pessoais quando utiliza a nossa loja online, em conformidade com o RGPD (UE) 2016/679 e a LOPDGDD.' ),
		'doroshopping_ui_legal_privacy_h1' => array( '1. Data controller', '1. Verantwortlicher', '1. Responsable du traitement', '1. Titolare del trattamento', '1. Responsável pelo tratamento' ),
		'doroshopping_ui_legal_privacy_p1' => array( 'The controller is the owner of %s. Corporate contact details and registered address are set out in the Legal notice.', 'Verantwortlicher ist der Inhaber von %s. Die Unternehmens-Kontaktdaten und der Sitz sind im Impressum angegeben.', 'Le responsable est le titulaire de %s. Les coordonnées de l’entreprise et le siège social sont indiqués dans les mentions légales.', 'Il titolare è il proprietario di %s. I contatti aziendali e la sede legale sono indicati nelle Note legali.', 'O responsável é o titular de %s. Os contactos empresariais e a sede social são indicados no Aviso legal.' ),
		'doroshopping_ui_legal_privacy_h2' => array( '2. Data we process', '2. Von uns verarbeitete Daten', '2. Données que nous traitons', '2. Dati trattati', '2. Dados que tratamos' ),
		'doroshopping_ui_legal_privacy_li1' => array( 'Identification and contact details: first name, surname, email, telephone number, shipping/billing address.', 'Identifikations- und Kontaktdaten: Vorname, Nachname, E-Mail, Telefonnummer, Liefer-/Rechnungsadresse.', 'Données d’identification et de contact : prénom, nom, e-mail, téléphone, adresse de livraison/facturation.', 'Dati identificativi e di contatto: nome, cognome, e-mail, telefono, indirizzo di spedizione/fatturazione.', 'Dados de identificação e contacto: nome, apelido, e-mail, telefone, morada de envio/faturação.' ),
		'doroshopping_ui_legal_privacy_li2' => array( 'Account and order data: purchase history, preferences and incidents.', 'Konto- und Bestelldaten: Kaufhistorie, Präferenzen und Vorfälle.', 'Données de compte et de commande : historique d’achat, préférences et incidents.', 'Dati dell’account e degli ordini: cronologia acquisti, preferenze e problemi.', 'Dados de conta e encomendas: histórico de compras, preferências e incidências.' ),
		'doroshopping_ui_legal_privacy_li3' => array( 'Technical data: IP address, cookies and browsing metrics (see Cookie Policy).', 'Technische Daten: IP-Adresse, Cookies und Navigationsmetriken (siehe Cookie-Richtlinie).', 'Données techniques : adresse IP, cookies et métriques de navigation (voir la Politique de cookies).', 'Dati tecnici: IP, cookie e metriche di navigazione (vedi la Politica sui cookie).', 'Dados técnicos: IP, cookies e métricas de navegação (consulte a Política de cookies).' ),
		'doroshopping_ui_legal_privacy_li4' => array( 'Payment data: processed by secure gateways; we do not store the full card number.', 'Zahlungsdaten: von sicheren Zahlungsanbietern verarbeitet; wir speichern keine vollständige Kartennummer.', 'Données de paiement : traitées par des passerelles sécurisées ; nous ne stockons pas le numéro complet de la carte.', 'Dati di pagamento: gestiti da gateway sicuri; non memorizziamo il numero completo della carta.', 'Dados de pagamento: processados por plataformas seguras; não armazenamos o número completo do cartão.' ),
		'doroshopping_ui_legal_privacy_h3' => array( '3. Purposes and legal basis', '3. Zwecke und Rechtsgrundlage', '3. Finalités et base juridique', '3. Finalità e base giuridica', '3. Finalidades e base legal' ),
		'doroshopping_ui_legal_privacy_li5' => array( 'Manage orders and customer service (performance of the contract).', 'Bestellungen und Kundenservice verwalten (Vertragserfüllung).', 'Gérer les commandes et le service client (exécution du contrat).', 'Gestire ordini e assistenza clienti (esecuzione del contratto).', 'Gerir encomendas e atendimento ao cliente (execução do contrato).' ),
		'doroshopping_ui_legal_privacy_li6' => array( 'Comply with legal obligations (tax and consumer law).', 'Gesetzliche Pflichten erfüllen (Steuer- und Verbraucherschutzrecht).', 'Respecter les obligations légales (fiscales et de consommation).', 'Adempiere agli obblighi di legge (fiscali e di consumo).', 'Cumprir obrigações legais (fiscais e de consumo).' ),
		'doroshopping_ui_legal_privacy_li7' => array( 'Improve the website and security (legitimate interest).', 'Website und Sicherheit verbessern (berechtigtes Interesse).', 'Améliorer le site et la sécurité (intérêt légitime).', 'Migliorare il sito web e la sicurezza (interesse legittimo).', 'Melhorar o site e a segurança (interesse legítimo).' ),
		'doroshopping_ui_legal_privacy_li8' => array( 'Send commercial updates only with your consent, where applicable.', 'Werbliche Neuigkeiten nur mit Ihrer Einwilligung senden, sofern erforderlich.', 'Envoyer des communications commerciales uniquement avec votre consentement, le cas échéant.', 'Inviare comunicazioni commerciali solo con il tuo consenso, ove applicabile.', 'Enviar novidades comerciais apenas com o seu consentimento, quando aplicável.' ),
		'doroshopping_ui_legal_privacy_h4' => array( '4. Recipients', '4. Empfänger', '4. Destinataires', '4. Destinatari', '4. Destinatários' ),
		'doroshopping_ui_legal_privacy_p4' => array( 'We may share data with logistics, payment, hosting and service providers under confidentiality agreements. We do not sell your data to third parties.', 'Wir können Daten mit Logistik-, Zahlungs-, Hosting- und Dienstleistern unter Vertraulichkeitsvereinbarungen teilen. Wir verkaufen Ihre Daten nicht an Dritte.', 'Nous pouvons partager des données avec des prestataires de logistique, de paiement, d’hébergement et de services, soumis à des accords de confidentialité. Nous ne vendons pas vos données à des tiers.', 'Possiamo condividere dati con fornitori di logistica, pagamenti, hosting e servizi, soggetti ad accordi di riservatezza. Non vendiamo i tuoi dati a terzi.', 'Podemos partilhar dados com fornecedores de logística, pagamento, alojamento e serviços, sujeitos a acordos de confidencialidade. Não vendemos os seus dados a terceiros.' ),
		'doroshopping_ui_legal_privacy_h5' => array( '5. Retention', '5. Aufbewahrung', '5. Conservation', '5. Conservazione', '5. Conservação' ),
		'doroshopping_ui_legal_privacy_p5' => array( 'We retain data for the time necessary for the business relationship and applicable statutory periods.', 'Wir bewahren Daten so lange auf, wie es für die Geschäftsbeziehung und die geltenden gesetzlichen Fristen erforderlich ist.', 'Nous conservons les données pendant la durée nécessaire à la relation commerciale et aux délais légaux applicables.', 'Conserviamo i dati per il tempo necessario al rapporto commerciale e ai termini di legge applicabili.', 'Conservamos os dados durante o tempo necessário à relação comercial e aos prazos legais aplicáveis.' ),
		'doroshopping_ui_legal_privacy_h6' => array( '6. Your rights', '6. Ihre Rechte', '6. Vos droits', '6. I tuoi diritti', '6. Os seus direitos' ),
		'doroshopping_ui_legal_privacy_p6' => array( 'You may request access, rectification, erasure, objection, restriction and portability by writing to the store contact address. You may also lodge a complaint with the AEPD (www.aepd.es).', 'Sie können Zugang, Berichtigung, Löschung, Widerspruch, Einschränkung und Datenübertragbarkeit über die Kontaktadresse des Shops verlangen. Sie können sich auch bei der AEPD (www.aepd.es) beschweren.', 'Vous pouvez demander l’accès, la rectification, l’effacement, l’opposition, la limitation et la portabilité en écrivant à l’adresse de contact de la boutique. Vous pouvez également déposer une réclamation auprès de l’AEPD (www.aepd.es).', 'Puoi richiedere accesso, rettifica, cancellazione, opposizione, limitazione e portabilità scrivendo all’indirizzo di contatto del negozio. Puoi anche presentare un reclamo all’AEPD (www.aepd.es).', 'Pode solicitar acesso, retificação, eliminação, oposição, limitação e portabilidade escrevendo para o contacto da loja. Pode também apresentar reclamação junto da AEPD (www.aepd.es).' ),

		'doroshopping_ui_legal_notice_intro' => array( 'This legal notice governs use of the %s website. By browsing the website, you accept the conditions described here.', 'Dieses Impressum regelt die Nutzung der Website von %s. Durch die Nutzung der Website akzeptieren Sie die hier beschriebenen Bedingungen.', 'Ces mentions légales régissent l’utilisation du site web de %s. En naviguant sur le site, vous acceptez les conditions décrites ici.', 'Queste note legali disciplinano l’uso del sito web di %s. Navigando sul sito accetti le condizioni qui descritte.', 'Este aviso legal regula a utilização do site de %s. Ao navegar no site, aceita as condições aqui descritas.' ),
		'doroshopping_ui_legal_notice_h1' => array( '1. Identification details', '1. Angaben zur Identität', '1. Données d’identification', '1. Dati identificativi', '1. Dados identificativos' ),
		'doroshopping_ui_legal_notice_p1' => array( 'Website owner: complete the company name, tax ID, registered office and registration details (if applicable).', 'Website-Inhaber: Firmenname, Steuernummer, Sitz und Registerdaten (falls zutreffend) ergänzen.', 'Titulaire du site : compléter la raison sociale, le numéro fiscal, le siège social et les données d’immatriculation (le cas échéant).', 'Titolare del sito: completare ragione sociale, codice fiscale/partita IVA, sede legale e dati di iscrizione al registro (se applicabile).', 'Titular do site: complete a denominação social, NIF, sede social e dados de registo (se aplicável).' ),
		'doroshopping_ui_legal_notice_li1' => array( 'Contact email: atencionalcliente@doroshopping.com', 'Kontakt-E-Mail: atencionalcliente@doroshopping.com', 'E-mail de contact : atencionalcliente@doroshopping.com', 'E-mail di contatto: atencionalcliente@doroshopping.com', 'E-mail de contacto: atencionalcliente@doroshopping.com' ),
		'doroshopping_ui_legal_notice_li2' => array( 'Website: doroshopping.com and associated domains.', 'Website: doroshopping.com und zugehörige Domains.', 'Site web : doroshopping.com et domaines associés.', 'Sito web: doroshopping.com e domini associati.', 'Site: doroshopping.com e domínios associados.' ),
		'doroshopping_ui_legal_notice_h2' => array( '2. Purpose', '2. Zweck', '2. Objet', '2. Oggetto', '2. Objeto' ),
		'doroshopping_ui_legal_notice_p2' => array( 'The website provides commercial information and the ability to purchase products online. The owner may change content, prices and availability without notice, without affecting orders already confirmed.', 'Die Website bietet kommerzielle Informationen und die Möglichkeit, Produkte online zu erwerben. Der Inhaber kann Inhalte, Preise und Verfügbarkeit ohne Vorankündigung ändern, unbeschadet bereits bestätigter Bestellungen.', 'Le site fournit des informations commerciales et permet d’acheter des produits en ligne. Le titulaire peut modifier les contenus, les prix et la disponibilité sans préavis, sans affecter les commandes déjà confirmées.', 'Il sito offre informazioni commerciali e la possibilità di acquistare prodotti online. Il titolare può modificare contenuti, prezzi e disponibilità senza preavviso, senza pregiudicare gli ordini già confermati.', 'O site disponibiliza informação comercial e a possibilidade de adquirir produtos online. O titular pode alterar conteúdos, preços e disponibilidade sem aviso prévio, sem prejuízo de encomendas já confirmadas.' ),
		'doroshopping_ui_legal_notice_h3' => array( '3. Terms of use', '3. Nutzungsbedingungen', '3. Conditions d’utilisation', '3. Condizioni d’uso', '3. Condições de utilização' ),
		'doroshopping_ui_legal_notice_li3' => array( 'You must use the website lawfully and in compliance with applicable rules.', 'Sie müssen die Website rechtmäßig und im Einklang mit den geltenden Vorschriften nutzen.', 'Vous devez utiliser le site de manière licite et dans le respect de la réglementation en vigueur.', 'Devi usare il sito in modo lecito e nel rispetto delle norme vigenti.', 'Deve utilizar o site de forma lícita e respeitando as normas aplicáveis.' ),
		'doroshopping_ui_legal_notice_li4' => array( 'It is prohibited to alter, damage or interfere with the operation of the website or associated systems.', 'Es ist verboten, den Betrieb der Website oder verbundener Systeme zu verändern, zu beschädigen oder zu beeinträchtigen.', 'Il est interdit d’altérer, d’endommager ou d’entraver le fonctionnement du site ou des systèmes associés.', 'Non è consentito alterare, danneggiare o interferire con il funzionamento del sito o dei sistemi associati.', 'Não é permitido alterar, danificar ou interferir com o funcionamento do site ou dos sistemas associados.' ),
		'doroshopping_ui_legal_notice_li5' => array( 'You are responsible for the accuracy of the information you provide in orders and registration.', 'Sie sind für die Richtigkeit der Angaben verantwortlich, die Sie bei Bestellungen und der Registrierung machen.', 'Vous êtes responsable de l’exactitude des données fournies lors des commandes et de l’inscription.', 'Sei responsabile della veridicità dei dati forniti negli ordini e nella registrazione.', 'É responsável pela veracidade dos dados fornecidos em encomendas e no registo.' ),
		'doroshopping_ui_legal_notice_h4' => array( '4. Intellectual property', '4. Geistiges Eigentum', '4. Propriété intellectuelle', '4. Proprietà intellettuale', '4. Propriedade intelectual' ),
		'doroshopping_ui_legal_notice_p4' => array( 'Texts, designs, logos, images and website code are protected. Reproduction, distribution or transformation without authorisation is prohibited, except where permitted by law.', 'Texte, Designs, Logos, Bilder und Website-Code sind geschützt. Vervielfältigung, Verbreitung oder Bearbeitung ohne Genehmigung ist verboten, außer soweit gesetzlich zulässig.', 'Les textes, dessins, logos, images et le code du site sont protégés. Leur reproduction, distribution ou transformation sans autorisation est interdite, sauf usages autorisés par la loi.', 'Testi, design, loghi, immagini e codice del sito sono protetti. Ne sono vietate riproduzione, distribuzione o trasformazione senza autorizzazione, salvo usi consentiti dalla legge.', 'Os textos, designs, logótipos, imagens e código do site estão protegidos. É proibida a sua reprodução, distribuição ou transformação sem autorização, salvo usos permitidos por lei.' ),
		'doroshopping_ui_legal_notice_h5' => array( '5. Liability', '5. Haftung', '5. Responsabilité', '5. Responsabilità', '5. Responsabilidade' ),
		'doroshopping_ui_legal_notice_p5' => array( 'We do not guarantee that there will be no interruptions or technical errors. We are not liable for damage caused by misuse of the website or linked third-party content, without prejudice to applicable consumer-law obligations for product sales.', 'Wir garantieren nicht, dass es keine Unterbrechungen oder technischen Fehler gibt. Wir haften nicht für Schäden aus missbräuchlicher Nutzung der Website oder verlinkten Inhalten Dritter, unbeschadet der geltenden Verbraucherschutzpflichten beim Produktverkauf.', 'Nous ne garantissons pas l’absence totale d’interruptions ou d’erreurs techniques. Nous ne répondons pas des dommages résultant d’une mauvaise utilisation du site ou de contenus de tiers liés, sans préjudice des obligations applicables en matière de consommation pour la vente de produits.', 'Non garantiamo l’assenza totale di interruzioni o errori tecnici. Non rispondiamo di danni derivanti dall’uso improprio del sito o da contenuti di terzi collegati, fatti salvi gli obblighi di consumo applicabili alla vendita di prodotti.', 'Não garantimos a ausência total de interrupções ou erros técnicos. Não respondemos por danos decorrentes do uso indevido do site ou de conteúdos de terceiros ligados, sem prejuízo das obrigações de consumo aplicáveis à venda de produtos.' ),
		'doroshopping_ui_legal_notice_h6' => array( '6. Applicable law', '6. Anwendbares Recht', '6. Droit applicable', '6. Legislazione applicabile', '6. Legislação aplicável' ),
		'doroshopping_ui_legal_notice_p6' => array( 'This notice is governed by applicable Spanish and European law. In disputes, the competent courts will be those determined by consumer legislation where applicable.', 'Dieses Impressum unterliegt dem anwendbaren spanischen und europäischen Recht. Bei Streitigkeiten sind die nach Verbraucherschutzrecht zuständigen Gerichte zuständig, sofern anwendbar.', 'Ces mentions sont régies par le droit espagnol et européen applicable. En cas de litige, les tribunaux compétents seront ceux prévus par la réglementation sur les consommateurs, le cas échéant.', 'Questo avviso è regolato dalla legislazione spagnola ed europea applicabile. In caso di controversie, saranno competenti i tribunali previsti dalla normativa sui consumatori, ove applicabile.', 'Este aviso rege-se pela legislação espanhola e europeia aplicável. Em caso de litígio, serão competentes os tribunais previstos pela legislação do consumidor, quando aplicável.' ),

		'doroshopping_ui_legal_terms_intro' => array( 'These general terms govern purchases from %s. By placing an order, you accept these terms together with the Privacy Policy and, where applicable, the Cookie Policy.', 'Diese allgemeinen Bedingungen regeln Käufe bei %s. Mit einer Bestellung akzeptieren Sie diese Bedingungen zusammen mit der Datenschutzerklärung und gegebenenfalls der Cookie-Richtlinie.', 'Ces conditions générales régissent les achats sur %s. En passant une commande, vous acceptez ces conditions ainsi que la Politique de confidentialité et, le cas échéant, la Politique de cookies.', 'Queste condizioni generali regolano gli acquisti su %s. Effettuando un ordine accetti queste condizioni insieme all’Informativa sulla privacy e, se applicabile, alla Politica sui cookie.', 'Estas condições gerais regulam as compras em %s. Ao fazer uma encomenda, aceita estas condições juntamente com a Política de Privacidade e, se aplicável, a Política de cookies.' ),
		'doroshopping_ui_legal_terms_h1' => array( '1. Scope and acceptance', '1. Geltungsbereich und Annahme', '1. Champ d’application et acceptation', '1. Ambito e accettazione', '1. Âmbito e aceitação' ),
		'doroshopping_ui_legal_terms_p1' => array( 'These terms apply to all orders placed through the online store. If you disagree, do not use the purchasing service.', 'Diese Bedingungen gelten für alle über den Onlineshop getätigten Bestellungen. Wenn Sie nicht einverstanden sind, nutzen Sie den Kaufservice nicht.', 'Ces conditions s’appliquent à toutes les commandes effectuées via la boutique en ligne. Si vous n’êtes pas d’accord, n’utilisez pas le service d’achat.', 'Le condizioni si applicano a tutti gli ordini effettuati tramite il negozio online. Se non sei d’accordo, non utilizzare il servizio di acquisto.', 'Estas condições aplicam-se a todas as encomendas realizadas através da loja online. Se não concordar, não utilize o serviço de compra.' ),
		'doroshopping_ui_legal_terms_h2' => array( '2. Products and information', '2. Produkte und Informationen', '2. Produits et informations', '2. Prodotti e informazioni', '2. Produtos e informações' ),
		'doroshopping_ui_legal_terms_p2' => array( 'Product pages include descriptions, prices and indicative shipping information where available. Images are illustrative. We strive to keep information up to date; contact support if there are material discrepancies.', 'Produktseiten enthalten Beschreibungen, Preise und, sofern verfügbar, unverbindliche Versandinformationen. Bilder dienen der Veranschaulichung. Wir bemühen uns um aktuelle Informationen; bei erheblichen Abweichungen kontaktieren Sie bitte den Support.', 'Les fiches produits comprennent une description, le prix et des informations indicatives de livraison lorsqu’elles sont disponibles. Les images sont illustratives. Nous nous efforçons de tenir les informations à jour ; en cas d’écart important, contactez le support.', 'Le schede prodotto includono descrizione, prezzo e informazioni indicative sulla spedizione quando disponibili. Le immagini sono illustrative. Ci impegniamo a mantenere aggiornate le informazioni; in caso di discrepanze rilevanti, contatta l’assistenza.', 'As fichas de produto incluem descrição, preço e informação indicativa de envio quando disponível. As imagens são ilustrativas. Procuramos manter a informação atualizada; em caso de discrepâncias relevantes, contacte o apoio.' ),
		'doroshopping_ui_legal_terms_h3' => array( '3. Prices and payments', '3. Preise und Zahlungen', '3. Prix et paiements', '3. Prezzi e pagamenti', '3. Preços e pagamentos' ),
		'doroshopping_ui_legal_terms_li1' => array( 'Prices are shown in the currency indicated in the store and include taxes where stated.', 'Preise werden in der im Shop angegebenen Währung angezeigt und enthalten Steuern, soweit angegeben.', 'Les prix sont affichés dans la devise indiquée dans la boutique et incluent les taxes lorsque cela est précisé.', 'I prezzi sono mostrati nella valuta indicata nel negozio e includono le imposte quando specificato.', 'Os preços são apresentados na moeda indicada na loja e incluem impostos quando tal for indicado.' ),
		'doroshopping_ui_legal_terms_li2' => array( 'Shipping costs are calculated before the order is confirmed.', 'Versandkosten werden vor der Bestellbestätigung berechnet.', 'Les frais de livraison sont calculés avant la confirmation de la commande.', 'Il costo di spedizione viene calcolato prima della conferma dell’ordine.', 'O custo de envio é calculado antes de confirmar a encomenda.' ),
		'doroshopping_ui_legal_terms_li3' => array( 'Payment is made through the gateways enabled at checkout.', 'Die Zahlung erfolgt über die an der Kasse aktivierten Zahlungsanbieter.', 'Le paiement s’effectue via les passerelles disponibles lors du paiement.', 'Il pagamento viene effettuato tramite i gateway abilitati al checkout.', 'O pagamento é efetuado através das plataformas disponíveis no checkout.' ),
		'doroshopping_ui_legal_terms_h4' => array( '4. Orders and contract', '4. Bestellungen und Vertrag', '4. Commandes et contrat', '4. Ordini e contratto', '4. Encomendas e contrato' ),
		'doroshopping_ui_legal_terms_p4' => array( 'An order constitutes an offer to purchase. Acceptance is confirmed by email and/or a change in order status. We may reject orders due to an obvious pricing error, lack of stock, suspected fraud or incomplete data.', 'Eine Bestellung stellt ein Kaufangebot dar. Die Annahme wird per E-Mail und/oder durch eine Änderung des Bestellstatus bestätigt. Wir können Bestellungen wegen offensichtlicher Preisfehler, fehlender Lagerbestände, Betrugsverdacht oder unvollständiger Daten ablehnen.', 'La commande constitue une offre d’achat. L’acceptation est confirmée par e-mail et/ou par un changement de statut de la commande. Nous pouvons refuser des commandes en cas d’erreur manifeste de prix, de rupture de stock, de suspicion de fraude ou de données incomplètes.', 'L’ordine costituisce un’offerta di acquisto. L’accettazione è confermata via e-mail e/o con il cambio di stato dell’ordine. Possiamo rifiutare ordini per evidente errore di prezzo, mancanza di stock, sospetta frode o dati incompleti.', 'A encomenda constitui uma oferta de compra. A aceitação é confirmada por e-mail e/ou por alteração do estado da encomenda. Podemos recusar encomendas por erro manifesto de preço, falta de stock, suspeita de fraude ou dados incompletos.' ),
		'doroshopping_ui_legal_terms_h5' => array( '5. Shipping and delivery', '5. Versand und Lieferung', '5. Expédition et livraison', '5. Spedizione e consegna', '5. Envios e entrega' ),
		'doroshopping_ui_legal_terms_p5' => array( 'Delivery times are estimates. The risk of loss or damage passes in accordance with applicable law. You must provide a correct and accessible delivery address.', 'Lieferzeiten sind Schätzwerte. Das Risiko von Verlust oder Beschädigung geht gemäß dem anwendbaren Recht über. Sie müssen eine korrekte und erreichbare Lieferadresse angeben.', 'Les délais de livraison sont estimatifs. Le risque de perte ou de détérioration est transféré conformément à la réglementation applicable. Vous devez fournir une adresse de livraison correcte et accessible.', 'I tempi di consegna sono stimati. Il rischio di perdita o deterioramento si trasferisce secondo la normativa applicabile. Devi fornire un indirizzo di consegna corretto e accessibile.', 'Os prazos de entrega são estimados. O risco de perda ou deterioração transfere-se de acordo com a legislação aplicável. Deve fornecer uma morada de entrega correta e acessível.' ),
		'doroshopping_ui_legal_terms_h6' => array( '6. Withdrawal and returns', '6. Widerruf und Rückgaben', '6. Rétractation et retours', '6. Recesso e resi', '6. Livre resolução e devoluções' ),
		'doroshopping_ui_legal_terms_p6' => array( 'If you are an EU consumer, you have a legal right of withdrawal (normally 14 days from receipt), subject to the applicable exceptions. See the Returns Policy for the procedure.', 'Wenn Sie Verbraucher in der EU sind, haben Sie ein gesetzliches Widerrufsrecht (in der Regel 14 Tage ab Erhalt), vorbehaltlich der geltenden Ausnahmen. Das Verfahren finden Sie in der Rückgaberichtlinie.', 'Si vous êtes consommateur dans l’UE, vous disposez d’un droit légal de rétractation (généralement 14 jours à compter de la réception), sous réserve des exceptions prévues. Consultez la Politique de retours pour la procédure.', 'Se sei un consumatore nell’UE, disponi del diritto di recesso nei termini di legge (normalmente 14 giorni dal ricevimento), con le eccezioni previste. Consulta la Politica sui resi per la procedura.', 'Se for consumidor na UE, dispõe do direito legal de livre resolução (normalmente 14 dias após a receção), com as exceções previstas. Consulte a Política de devoluções para o procedimento.' ),
		'doroshopping_ui_legal_terms_h7' => array( '7. Warranty', '7. Gewährleistung', '7. Garantie', '7. Garanzia', '7. Garantia' ),
		'doroshopping_ui_legal_terms_p7' => array( 'Products are covered by the legal guarantee of conformity. Keep your invoice or order confirmation to manage any claim.', 'Für Produkte gilt die gesetzliche Gewährleistung der Konformität. Bewahren Sie die Rechnung oder Bestellbestätigung für mögliche Ansprüche auf.', 'Les produits bénéficient de la garantie légale de conformité. Conservez la facture ou la confirmation de commande pour toute réclamation.', 'I prodotti beneficiano della garanzia legale di conformità. Conserva la fattura o la conferma dell’ordine per gestire eventuali reclami.', 'Os produtos beneficiam da garantia legal de conformidade. Guarde a fatura ou a confirmação da encomenda para qualquer reclamação.' ),
		'doroshopping_ui_legal_terms_h8' => array( '8. Account use', '8. Nutzung des Kontos', '8. Utilisation du compte', '8. Uso dell’account', '8. Utilização da conta' ),
		'doroshopping_ui_legal_terms_p8' => array( 'You are responsible for keeping your credentials secure. Notify us of any unauthorised use of your account.', 'Sie sind für die sichere Aufbewahrung Ihrer Zugangsdaten verantwortlich. Informieren Sie uns über jede unbefugte Nutzung Ihres Kontos.', 'Vous êtes responsable de la conservation de vos identifiants. Informez-nous de toute utilisation non autorisée de votre compte.', 'Sei responsabile della custodia delle tue credenziali. Comunicaci qualsiasi uso non autorizzato del tuo account.', 'É responsável por guardar as suas credenciais em segurança. Informe-nos de qualquer utilização não autorizada da sua conta.' ),
		'doroshopping_ui_legal_terms_h9' => array( '9. Changes', '9. Änderungen', '9. Modifications', '9. Modifiche', '9. Alterações' ),
		'doroshopping_ui_legal_terms_p9' => array( 'We may update these terms. The version in force is the one published on this page on the purchase date.', 'Wir können diese Bedingungen aktualisieren. Die gültige Fassung ist die an diesem Tag des Kaufs auf dieser Seite veröffentlichte.', 'Nous pouvons mettre à jour ces conditions. La version en vigueur est celle publiée sur cette page à la date de l’achat.', 'Possiamo aggiornare queste condizioni. La versione vigente è quella pubblicata in questa pagina alla data dell’acquisto.', 'Podemos atualizar estas condições. A versão em vigor é a publicada nesta página na data da compra.' ),
		'doroshopping_ui_legal_terms_h10' => array( '10. Contact', '10. Kontakt', '10. Contact', '10. Contatto', '10. Contacto' ),
		'doroshopping_ui_legal_terms_p10' => array( 'For contractual or order questions: atencionalcliente@doroshopping.com or the Help Centre.', 'Bei Fragen zu Verträgen oder Bestellungen: atencionalcliente@doroshopping.com oder das Hilfe-Center.', 'Pour toute question contractuelle ou relative aux commandes : atencionalcliente@doroshopping.com ou le Centre d’aide.', 'Per dubbi contrattuali o sugli ordini: atencionalcliente@doroshopping.com oppure il Centro assistenza.', 'Para dúvidas contratuais ou sobre encomendas: atencionalcliente@doroshopping.com ou o Centro de ajuda.' ),

		'doroshopping_ui_legal_cookies_intro' => array( 'This Cookie Policy explains what cookies are, which ones we use and how you can manage them.', 'Diese Cookie-Richtlinie erklärt, was Cookies sind, welche wir verwenden und wie Sie sie verwalten können.', 'Cette Politique de cookies explique ce que sont les cookies, lesquels nous utilisons et comment vous pouvez les gérer.', 'Questa Politica sui cookie spiega cosa sono i cookie, quali utilizziamo e come puoi gestirli.', 'Esta Política de cookies explica o que são cookies, quais utilizamos e como pode geri-los.' ),
		'doroshopping_ui_legal_cookies_h1' => array( '1. What are cookies?', '1. Was sind Cookies?', '1. Que sont les cookies ?', '1. Cosa sono i cookie?', '1. O que são cookies?' ),
		'doroshopping_ui_legal_cookies_p1' => array( 'They are small files that the website or third parties store on your device to remember preferences, maintain a session, analyse use or personalise content.', 'Es handelt sich um kleine Dateien, die die Website oder Dritte auf Ihrem Gerät speichern, um Präferenzen zu merken, Sitzungen aufrechtzuerhalten, die Nutzung zu analysieren oder Inhalte zu personalisieren.', 'Ce sont de petits fichiers que le site ou des tiers enregistrent sur votre appareil pour mémoriser vos préférences, maintenir la session, analyser l’utilisation ou personnaliser les contenus.', 'Sono piccoli file che il sito o terzi salvano sul tuo dispositivo per ricordare preferenze, mantenere la sessione, analizzare l’uso o personalizzare contenuti.', 'São pequenos ficheiros que o site ou terceiros guardam no seu dispositivo para recordar preferências, manter a sessão, analisar a utilização ou personalizar conteúdos.' ),
		'doroshopping_ui_legal_cookies_h2' => array( '2. Types of cookies we may use', '2. Arten von Cookies, die wir verwenden können', '2. Types de cookies que nous pouvons utiliser', '2. Tipi di cookie che possiamo utilizzare', '2. Tipos de cookies que podemos utilizar' ),
		'doroshopping_ui_legal_cookies_li1' => array( 'Technical / necessary: allow browsing, use of the cart, checkout and website security.', 'Technische / notwendige Cookies: ermöglichen Navigation, Warenkorb, Kasse und Website-Sicherheit.', 'Techniques / nécessaires : permettent la navigation, l’utilisation du panier, le paiement et la sécurité du site.', 'Tecnici / necessari: consentono la navigazione, l’uso del carrello, il checkout e la sicurezza del sito.', 'Técnicos / necessários: permitem navegar, usar o carrinho, o checkout e a segurança do site.' ),
		'doroshopping_ui_legal_cookies_li2' => array( 'Preferences: remember language, location or currency where applicable.', 'Präferenzen: merken sich Sprache, Standort oder Währung, sofern zutreffend.', 'Préférences : mémorisent la langue, le lieu ou la devise, le cas échéant.', 'Preferenze: ricordano lingua, posizione o valuta, ove applicabile.', 'Preferências: recordam idioma, localização ou moeda, quando aplicável.' ),
		'doroshopping_ui_legal_cookies_li3' => array( 'Analytics: help us understand aggregated website usage.', 'Analyse-Cookies: helfen uns, die Nutzung der Website in aggregierter Form zu verstehen.', 'Analytiques : aident à comprendre l’utilisation du site de manière agrégée.', 'Analitici: aiutano a comprendere l’uso del sito in forma aggregata.', 'Analíticos: ajudam a compreender a utilização do site de forma agregada.' ),
		'doroshopping_ui_legal_cookies_li4' => array( 'Marketing: only if you accept them and they are enabled, to measure campaigns.', 'Marketing: nur wenn Sie zustimmen und sie aktiviert sind, um Kampagnen zu messen.', 'Marketing : uniquement si vous les acceptez et qu’ils sont activés, afin de mesurer les campagnes.', 'Marketing: solo se li accetti e sono attivati, per misurare le campagne.', 'Marketing: apenas se os aceitar e estiverem ativos, para medir campanhas.' ),
		'doroshopping_ui_legal_cookies_h3' => array( '3. Legal basis', '3. Rechtsgrundlage', '3. Base juridique', '3. Base giuridica', '3. Base legal' ),
		'doroshopping_ui_legal_cookies_p3' => array( 'Necessary cookies are based on legitimate interest / performance of the service. The rest require your consent where required by law.', 'Notwendige Cookies beruhen auf berechtigtem Interesse / Erbringung des Dienstes. Die übrigen erfordern Ihre Einwilligung, wenn das Gesetz dies verlangt.', 'Les cookies nécessaires reposent sur l’intérêt légitime / l’exécution du service. Les autres nécessitent votre consentement lorsque la réglementation l’exige.', 'I cookie necessari si basano sul legittimo interesse / esecuzione del servizio. Gli altri richiedono il tuo consenso quando la normativa lo esige.', 'Os cookies necessários baseiam-se no interesse legítimo / execução do serviço. Os restantes requerem o seu consentimento quando a legislação o exigir.' ),
		'doroshopping_ui_legal_cookies_h4' => array( '4. How to manage cookies', '4. So verwalten Sie Cookies', '4. Comment gérer les cookies', '4. Come gestire i cookie', '4. Como gerir cookies' ),
		'doroshopping_ui_legal_cookies_li5' => array( 'You can configure your browser to block or delete cookies.', 'Sie können Ihren Browser so einstellen, dass Cookies blockiert oder gelöscht werden.', 'Vous pouvez configurer votre navigateur pour bloquer ou supprimer les cookies.', 'Puoi configurare il browser per bloccare o eliminare i cookie.', 'Pode configurar o seu navegador para bloquear ou eliminar cookies.' ),
		'doroshopping_ui_legal_cookies_li6' => array( 'If we use a consent banner, you can accept, reject or configure non-essential categories.', 'Wenn wir ein Einwilligungsbanner verwenden, können Sie nicht notwendige Kategorien akzeptieren, ablehnen oder konfigurieren.', 'Si nous utilisons une bannière de consentement, vous pourrez accepter, refuser ou configurer les catégories non essentielles.', 'Se utilizziamo un banner di consenso, puoi accettare, rifiutare o configurare le categorie non essenziali.', 'Se utilizarmos uma faixa de consentimento, poderá aceitar, recusar ou configurar categorias não essenciais.' ),
		'doroshopping_ui_legal_cookies_li7' => array( 'Blocking necessary cookies may prevent the cart or login from working.', 'Das Blockieren notwendiger Cookies kann die Funktion von Warenkorb oder Anmeldung beeinträchtigen.', 'Bloquer les cookies nécessaires peut empêcher le fonctionnement du panier ou de la connexion.', 'Bloccare i cookie necessari può impedire il funzionamento del carrello o del login.', 'Bloquear cookies necessários pode impedir o funcionamento do carrinho ou do início de sessão.' ),
		'doroshopping_ui_legal_cookies_h5' => array( '5. More information', '5. Weitere Informationen', '5. Plus d’informations', '5. Maggiori informazioni', '5. Mais informações' ),
		'doroshopping_ui_legal_cookies_p5' => array( 'For personal-data processing, see the Privacy Policy. Contact: atencionalcliente@doroshopping.com.', 'Informationen zur Verarbeitung personenbezogener Daten finden Sie in der Datenschutzerklärung. Kontakt: atencionalcliente@doroshopping.com.', 'Pour le traitement des données personnelles, consultez la Politique de confidentialité. Contact : atencionalcliente@doroshopping.com.', 'Per il trattamento dei dati personali, consulta l’Informativa sulla privacy. Contatto: atencionalcliente@doroshopping.com.', 'Para o tratamento de dados pessoais, consulte a Política de Privacidade. Contacto: atencionalcliente@doroshopping.com.' ),
	);

	$packs = array(
		'en' => array(),
		'de' => array(),
		'fr' => array(),
		'it' => array(),
		'pt' => array(),
	);

	foreach ( $entries as $key => $texts ) {
		$packs['en'][ $key ] = $texts[0];
		$packs['de'][ $key ] = $texts[1];
		$packs['fr'][ $key ] = $texts[2];
		$packs['it'][ $key ] = $texts[3];
		$packs['pt'][ $key ] = $texts[4];
	}

	return $packs;
}
