<?php
/**
 * UI translations for support pages.
 *
 * @package Doroshopping
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Packs UI páginas de soporte (envíos, ayuda, FAQ, pagos, protección, wishlist).
 *
 * @return array<string, array<string, string>> lang => key => text
 */
function doroshopping_i18n_builtin_ui_support_packs() {
	$entries = array(
		// Shipping.
		'doroshopping_ui_shippage_eyebrow' => array( 'Logistics', 'Logistik', 'Logistique', 'Logistica', 'Logística' ),
		'doroshopping_ui_shippage_title' => array( 'Shipping', 'Versand', 'Livraison', 'Spedizioni', 'Envios' ),
		'doroshopping_ui_shippage_lead' => array( 'Indicative delivery times, costs in the cart and order tracking. The final estimate depends on the destination and product.', 'Voraussichtliche Lieferzeiten, Kosten im Warenkorb und Sendungsverfolgung. Die endgültige Schätzung hängt von Zielort und Produkt ab.', 'Délais indicatifs, frais dans le panier et suivi de commande. L’estimation finale dépend de la destination et du produit.', 'Tempi indicativi, costi nel carrello e tracciamento dell’ordine. La stima finale dipende dalla destinazione e dal prodotto.', 'Prazos indicativos, custos no carrinho e rastreio da encomenda. A estimativa final depende do destino e do produto.' ),
		'doroshopping_ui_shippage_howto' => array( 'How your order arrives', 'So kommt Ihre Bestellung an', 'Comment votre commande arrive', 'Come arriva il tuo ordine', 'Como chega a sua encomenda' ),
		'doroshopping_ui_shippage_s1_title' => array( 'Confirmation', 'Bestätigung', 'Confirmation', 'Conferma', 'Confirmação' ),
		'doroshopping_ui_shippage_s1_text' => array( 'After payment, you will receive a confirmation email with your order summary.', 'Nach der Zahlung erhalten Sie eine Bestätigungs-E-Mail mit Ihrer Bestellübersicht.', 'Après le paiement, vous recevrez un e-mail de confirmation avec le récapitulatif de votre commande.', 'Dopo il pagamento riceverai un’e-mail di conferma con il riepilogo dell’ordine.', 'Após o pagamento, receberá um e-mail de confirmação com o resumo da sua encomenda.' ),
		'doroshopping_ui_shippage_s2_title' => array( 'Preparation and dispatch', 'Vorbereitung und Versand', 'Préparation et expédition', 'Preparazione e spedizione', 'Preparação e expedição' ),
		'doroshopping_ui_shippage_s2_text' => array( 'Your order is prepared and handed to the carrier. Dispatch times vary according to stock and origin.', 'Ihre Bestellung wird vorbereitet und an den Versanddienstleister übergeben. Die Bearbeitungszeit variiert je nach Bestand und Herkunft.', 'Votre commande est préparée et remise au transporteur. Les délais d’expédition varient selon le stock et l’origine.', 'Il tuo ordine viene preparato e affidato al corriere. I tempi di spedizione variano in base alla disponibilità e all’origine.', 'A sua encomenda é preparada e entregue à transportadora. Os prazos de expedição variam conforme o stock e a origem.' ),
		'doroshopping_ui_shippage_s3_title' => array( 'Tracking', 'Sendungsverfolgung', 'Suivi', 'Tracciamento', 'Rastreio' ),
		'doroshopping_ui_shippage_s3_text' => array( 'When tracking is available, you will see it by email and in My account → Orders.', 'Sobald die Sendungsverfolgung verfügbar ist, finden Sie sie per E-Mail und unter Mein Konto → Bestellungen.', 'Lorsque le suivi est disponible, vous le trouverez par e-mail et dans Mon compte → Commandes.', 'Quando il tracking sarà disponibile, lo troverai via e-mail e in Il mio account → Ordini.', 'Quando o rastreio estiver disponível, poderá consultá-lo por e-mail e em A minha conta → Encomendas.' ),
		'doroshopping_ui_shippage_zones_title' => array( 'Zones and delivery times', 'Zonen und Lieferzeiten', 'Zones et délais', 'Zone e tempi di consegna', 'Zonas e prazos' ),
		'doroshopping_ui_shippage_zones_1' => array( 'Mainland Spain and the EU: usually from a few days to a couple of weeks after dispatch.', 'Spanisches Festland und EU: normalerweise einige Tage bis ein paar Wochen nach dem Versand.', 'Espagne continentale et UE : généralement de quelques jours à deux semaines après l’expédition.', 'Spagna continentale e UE: in genere da alcuni giorni a un paio di settimane dopo la spedizione.', 'Espanha continental e UE: normalmente de alguns dias a algumas semanas após a expedição.' ),
		'doroshopping_ui_shippage_zones_2' => array( 'Islands, remote areas or destinations outside the EU: longer delivery times and possible additional formalities.', 'Inseln, abgelegene Gebiete oder Ziele außerhalb der EU: längere Lieferzeiten und mögliche zusätzliche Formalitäten.', 'Îles, zones isolées ou destinations hors UE : délais plus longs et éventuelles formalités supplémentaires.', 'Isole, zone remote o destinazioni fuori dall’UE: tempi più lunghi e possibili formalità aggiuntive.', 'Ilhas, zonas remotas ou destinos fora da UE: prazos mais longos e possíveis formalidades adicionais.' ),
		'doroshopping_ui_shippage_zones_3' => array( 'Product pages show indicative estimates when available.', 'Produktseiten zeigen verfügbare voraussichtliche Lieferzeiten an.', 'Les fiches produit affichent des estimations indicatives lorsqu’elles sont disponibles.', 'Le pagine dei prodotti mostrano stime indicative quando disponibili.', 'As páginas de produto mostram estimativas indicativas quando disponíveis.' ),
		'doroshopping_ui_shippage_zones_note' => array( 'Delivery times are estimates and may be affected by peak demand, customs or carrier incidents.', 'Lieferzeiten sind Schätzungen und können durch hohe Nachfrage, Zoll oder Probleme beim Versanddienstleister beeinflusst werden.', 'Les délais sont indicatifs et peuvent être affectés par les pics de demande, les douanes ou des incidents du transporteur.', 'I tempi sono indicativi e possono essere influenzati da picchi di domanda, dogana o inconvenienti del corriere.', 'Os prazos são estimados e podem ser afetados por picos de procura, alfândega ou incidentes da transportadora.' ),
		'doroshopping_ui_shippage_costs_title' => array( 'Costs and customs', 'Kosten und Zoll', 'Frais et douanes', 'Costi e dogana', 'Custos e alfândega' ),
		'doroshopping_ui_shippage_costs_1' => array( 'Shipping costs are calculated in the cart based on address and weight/volume.', 'Die Versandkosten werden im Warenkorb anhand von Adresse und Gewicht/Volumen berechnet.', 'Les frais de livraison sont calculés dans le panier selon l’adresse et le poids/volume.', 'I costi di spedizione sono calcolati nel carrello in base all’indirizzo e al peso/volume.', 'Os custos de envio são calculados no carrinho com base na morada e no peso/volume.' ),
		'doroshopping_ui_shippage_costs_2' => array( 'For deliveries outside the EU, import duties or VAT may be charged to the recipient.', 'Bei Lieferungen außerhalb der EU können Einfuhrzölle oder Mehrwertsteuer zulasten des Empfängers anfallen.', 'Pour les livraisons hors UE, des droits de douane ou une TVA à l’importation peuvent être facturés au destinataire.', 'Per le spedizioni fuori dall’UE, dazi o IVA all’importazione possono essere a carico del destinatario.', 'Para envios fora da UE, podem aplicar-se direitos aduaneiros ou IVA de importação a cargo do destinatário.' ),
		'doroshopping_ui_shippage_costs_3' => array( 'Always check your address before paying to avoid delays or reshipments.', 'Prüfen Sie die Adresse vor der Zahlung, um Verzögerungen oder Nachsendungen zu vermeiden.', 'Vérifiez toujours votre adresse avant de payer afin d’éviter les retards ou les réexpéditions.', 'Controlla sempre l’indirizzo prima di pagare per evitare ritardi o nuove spedizioni.', 'Confirme sempre a morada antes de pagar para evitar atrasos ou reenvios.' ),
		'doroshopping_ui_shippage_returns_btn' => array( 'Returns policy', 'Rückgaberichtlinie', 'Politique de retours', 'Politica dei resi', 'Política de devoluções' ),
		'doroshopping_ui_shippage_where_title' => array( 'Where is my order?', 'Wo ist meine Bestellung?', 'Où est ma commande ?', 'Dov’è il mio ordine?', 'Onde está a minha encomenda?' ),
		'doroshopping_ui_shippage_where_text' => array( 'Check your account or contact support if tracking has not updated within 48–72 hours.', 'Prüfen Sie Ihr Konto oder kontaktieren Sie den Support, wenn sich die Sendungsverfolgung innerhalb von 48–72 Stunden nicht aktualisiert.', 'Consultez votre compte ou contactez le support si le suivi ne se met pas à jour sous 48 à 72 h.', 'Controlla il tuo account o contatta l’assistenza se il tracking non si aggiorna entro 48–72 ore.', 'Consulte a sua conta ou contacte o apoio se o rastreio não for atualizado em 48–72 h.' ),
		'doroshopping_ui_shippage_orders_btn' => array( 'View my orders', 'Meine Bestellungen anzeigen', 'Voir mes commandes', 'Visualizza i miei ordini', 'Ver as minhas encomendas' ),
		'doroshopping_ui_shippage_support_btn' => array( 'Contact support', 'Support kontaktieren', 'Contacter le support', 'Contatta l’assistenza', 'Contactar o apoio' ),

		// Help centre.
		'doroshopping_ui_help_eyebrow' => array( 'Doroshopping Support', 'Doroshopping-Support', 'Support Doroshopping', 'Assistenza Doroshopping', 'Apoio Doroshopping' ),
		'doroshopping_ui_help_title' => array( 'Help centre', 'Hilfe-Center', 'Centre d’aide', 'Centro assistenza', 'Centro de ajuda' ),
		'doroshopping_ui_help_lead' => array( 'Have a question about your order, payment or return? Send us a message and our team will reply as soon as possible.', 'Haben Sie eine Frage zu Ihrer Bestellung, Zahlung oder Rückgabe? Senden Sie uns eine Nachricht, unser Team antwortet schnellstmöglich.', 'Une question sur votre commande, votre paiement ou un retour ? Envoyez-nous un message et notre équipe vous répondra dès que possible.', 'Hai una domanda sul tuo ordine, pagamento o reso? Inviaci un messaggio e il nostro team risponderà al più presto.', 'Tem uma questão sobre a sua encomenda, pagamento ou devolução? Envie-nos uma mensagem e a nossa equipa responderá assim que possível.' ),
		'doroshopping_ui_help_sent' => array( 'Message sent. We will reply to your email as soon as possible.', 'Nachricht gesendet. Wir antworten Ihnen schnellstmöglich per E-Mail.', 'Message envoyé. Nous vous répondrons par e-mail dès que possible.', 'Messaggio inviato. Ti risponderemo via e-mail al più presto.', 'Mensagem enviada. Responderemos para o seu e-mail assim que possível.' ),
		'doroshopping_ui_help_error' => array( 'We could not send your message. Check the fields and try again.', 'Ihre Nachricht konnte nicht gesendet werden. Prüfen Sie die Felder und versuchen Sie es erneut.', 'Nous n’avons pas pu envoyer votre message. Vérifiez les champs et réessayez.', 'Non siamo riusciti a inviare il messaggio. Controlla i campi e riprova.', 'Não foi possível enviar a sua mensagem. Verifique os campos e tente novamente.' ),
		'doroshopping_ui_help_form_title' => array( 'Support form', 'Supportformular', 'Formulaire d’assistance', 'Modulo di assistenza', 'Formulário de apoio' ),
		'doroshopping_ui_help_honeypot' => array( 'Website', 'Website', 'Site web', 'Sito web', 'Site' ),
		'doroshopping_ui_help_name' => array( 'Name', 'Name', 'Nom', 'Nome', 'Nome' ),
		'doroshopping_ui_help_email' => array( 'Email address', 'E-Mail-Adresse', 'Adresse e-mail', 'Indirizzo e-mail', 'Endereço de e-mail' ),
		'doroshopping_ui_help_phone' => array( 'Phone', 'Telefon', 'Téléphone', 'Telefono', 'Telefone' ),
		'doroshopping_ui_help_phone_ph' => array( 'E.g. +34 600 000 000', 'Z. B. +34 600 000 000', 'Ex. +34 600 000 000', 'Es. +34 600 000 000', 'Ex. +34 600 000 000' ),
		'doroshopping_ui_help_order' => array( 'Order number (optional)', 'Bestellnummer (optional)', 'Numéro de commande (facultatif)', 'Numero ordine (facoltativo)', 'Número da encomenda (opcional)' ),
		'doroshopping_ui_help_order_ph' => array( 'E.g. 10452', 'Z. B. 10452', 'Ex. 10452', 'Es. 10452', 'Ex. 10452' ),
		'doroshopping_ui_help_topic' => array( 'Topic', 'Thema', 'Sujet', 'Argomento', 'Assunto' ),
		'doroshopping_ui_help_topic_placeholder' => array( 'Select a topic', 'Thema auswählen', 'Sélectionnez un sujet', 'Seleziona un argomento', 'Selecione um assunto' ),
		'doroshopping_ui_help_topic_pedido' => array( 'Order / tracking', 'Bestellung / Sendungsverfolgung', 'Commande / suivi', 'Ordine / tracciamento', 'Encomenda / rastreio' ),
		'doroshopping_ui_help_topic_pago' => array( 'Payment / invoice', 'Zahlung / Rechnung', 'Paiement / facture', 'Pagamento / fattura', 'Pagamento / fatura' ),
		'doroshopping_ui_help_topic_envio' => array( 'Shipping / delivery', 'Versand / Lieferung', 'Livraison / réception', 'Spedizione / consegna', 'Envio / entrega' ),
		'doroshopping_ui_help_topic_devolucion' => array( 'Return / refund', 'Rückgabe / Erstattung', 'Retour / remboursement', 'Reso / rimborso', 'Devolução / reembolso' ),
		'doroshopping_ui_help_topic_producto' => array( 'Product / quality', 'Produkt / Qualität', 'Produit / qualité', 'Prodotto / qualità', 'Produto / qualidade' ),
		'doroshopping_ui_help_topic_cuenta' => array( 'Account / access', 'Konto / Zugang', 'Compte / accès', 'Account / accesso', 'Conta / acesso' ),
		'doroshopping_ui_help_topic_otro' => array( 'Other', 'Sonstiges', 'Autre', 'Altro', 'Outro' ),
		'doroshopping_ui_help_message' => array( 'Message', 'Nachricht', 'Message', 'Messaggio', 'Mensagem' ),
		'doroshopping_ui_help_message_ph' => array( 'Tell us what you need with as much detail as possible…', 'Schildern Sie uns Ihr Anliegen so detailliert wie möglich…', 'Indiquez-nous votre demande avec le plus de détails possible…', 'Spiegaci di cosa hai bisogno nel modo più dettagliato possibile…', 'Diga-nos do que precisa com o maior detalhe possível…' ),
		'doroshopping_ui_help_submit' => array( 'Send request', 'Anfrage senden', 'Envoyer la demande', 'Invia richiesta', 'Enviar pedido' ),
		'doroshopping_ui_help_whatsapp' => array( 'WhatsApp', 'WhatsApp', 'WhatsApp', 'WhatsApp', 'WhatsApp' ),
		'doroshopping_ui_help_meta' => array( 'Your message will be sent to atencionalcliente@doroshopping.com', 'Ihre Nachricht wird an atencionalcliente@doroshopping.com gesendet', 'Votre message sera envoyé à atencionalcliente@doroshopping.com', 'Il tuo messaggio verrà inviato a atencionalcliente@doroshopping.com', 'A sua mensagem será enviada para atencionalcliente@doroshopping.com' ),
		'doroshopping_ui_help_wa_aside_title' => array( 'WhatsApp', 'WhatsApp', 'WhatsApp', 'WhatsApp', 'WhatsApp' ),
		'doroshopping_ui_help_wa_aside_text' => array( 'If you prefer to chat with us, contact us on WhatsApp.', 'Wenn Sie lieber chatten möchten, kontaktieren Sie uns über WhatsApp.', 'Si vous préférez nous écrire par chat, contactez-nous sur WhatsApp.', 'Se preferisci scriverci in chat, contattaci su WhatsApp.', 'Se preferir falar connosco por chat, contacte-nos pelo WhatsApp.' ),
		'doroshopping_ui_help_wa_cta' => array( 'Message us on WhatsApp', 'Über WhatsApp schreiben', 'Écrire sur WhatsApp', 'Scrivici su WhatsApp', 'Escrever no WhatsApp' ),
		'doroshopping_ui_help_wa_soon' => array( 'You will soon also be able to contact us on WhatsApp.', 'Bald können Sie uns auch über WhatsApp schreiben.', 'Vous pourrez bientôt aussi nous écrire sur WhatsApp.', 'Presto potrai contattarci anche su WhatsApp.', 'Em breve também poderá contactar-nos pelo WhatsApp.' ),
		'doroshopping_ui_help_quick_title' => array( 'Quick help', 'Schnellhilfe', 'Aide rapide', 'Aiuto rapido', 'Ajuda rápida' ),
		'doroshopping_ui_help_link_faq' => array( 'Frequently asked questions', 'Häufig gestellte Fragen', 'Questions fréquentes', 'Domande frequenti', 'Perguntas frequentes' ),
		'doroshopping_ui_help_link_track' => array( 'Track my order', 'Bestellung verfolgen', 'Suivre ma commande', 'Traccia il mio ordine', 'Rastrear a minha encomenda' ),
		'doroshopping_ui_help_link_returns' => array( 'Returns and refunds', 'Rückgaben und Erstattungen', 'Retours et remboursements', 'Resi e rimborsi', 'Devoluções e reembolsos' ),
		'doroshopping_ui_help_link_shipping' => array( 'Shipping information', 'Versandinformationen', 'Informations de livraison', 'Informazioni sulla spedizione', 'Informações de envio' ),
		'doroshopping_ui_help_link_payments' => array( 'Payment methods', 'Zahlungsmethoden', 'Moyens de paiement', 'Metodi di pagamento', 'Métodos de pagamento' ),
		'doroshopping_ui_help_hours_title' => array( 'Customer service hours', 'Servicezeiten', 'Horaires du service client', 'Orari del servizio clienti', 'Horário de atendimento' ),
		'doroshopping_ui_help_hours_text' => array( 'Monday to Friday, 9:00–18:00 CET. We usually reply by email within 24–48 business hours.', 'Montag bis Freitag, 9:00–18:00 CET. Wir antworten normalerweise innerhalb von 24–48 Arbeitsstunden per E-Mail.', 'Du lundi au vendredi, de 9 h à 18 h CET. Nous répondons habituellement par e-mail sous 24 à 48 h ouvrées.', 'Dal lunedì al venerdì, 9:00–18:00 CET. Di solito rispondiamo via e-mail entro 24–48 ore lavorative.', 'De segunda a sexta, 9:00–18:00 CET. Normalmente respondemos por e-mail em 24–48 horas úteis.' ),

		// FAQ.
		'doroshopping_ui_faq_eyebrow' => array( 'Help', 'Hilfe', 'Aide', 'Aiuto', 'Ajuda' ),
		'doroshopping_ui_faq_title' => array( 'Frequently asked questions', 'Häufig gestellte Fragen', 'Questions fréquentes', 'Domande frequenti', 'Perguntas frequentes' ),
		'doroshopping_ui_faq_lead' => array( 'Quick answers about orders, payments, shipping, returns and your account. If you cannot find what you need, contact our team.', 'Schnelle Antworten zu Bestellungen, Zahlungen, Versand, Rückgaben und Ihrem Konto. Wenn Sie nicht finden, was Sie brauchen, kontaktieren Sie unser Team.', 'Des réponses rapides sur les commandes, les paiements, la livraison, les retours et votre compte. Si vous ne trouvez pas votre réponse, contactez notre équipe.', 'Risposte rapide su ordini, pagamenti, spedizioni, resi e account. Se non trovi ciò che cerchi, contatta il nostro team.', 'Respostas rápidas sobre encomendas, pagamentos, envios, devoluções e a sua conta. Se não encontrar o que procura, contacte a nossa equipa.' ),
		'doroshopping_ui_faq_contact_btn' => array( 'Contact support', 'Support kontaktieren', 'Contacter le support', 'Contatta l’assistenza', 'Contactar o apoio' ),
		'doroshopping_ui_faq_cat_orders' => array( 'Orders and account', 'Bestellungen und Konto', 'Commandes et compte', 'Ordini e account', 'Encomendas e conta' ),
		'doroshopping_ui_faq_cat_payments' => array( 'Payments', 'Zahlungen', 'Paiements', 'Pagamenti', 'Pagamentos' ),
		'doroshopping_ui_faq_cat_shipping' => array( 'Shipping', 'Versand', 'Livraison', 'Spedizioni', 'Envios' ),
		'doroshopping_ui_faq_cat_returns' => array( 'Returns and refunds', 'Rückgaben und Erstattungen', 'Retours et remboursements', 'Resi e rimborsi', 'Devoluções e reembolsos' ),
		'doroshopping_ui_faq_cat_products' => array( 'Products and warranty', 'Produkte und Garantie', 'Produits et garantie', 'Prodotti e garanzia', 'Produtos e garantia' ),
		'doroshopping_ui_faq_q_track' => array( 'How can I track my order?', 'Wie kann ich meine Bestellung verfolgen?', 'Comment puis-je suivre ma commande ?', 'Come posso tracciare il mio ordine?', 'Como posso rastrear a minha encomenda?' ),
		'doroshopping_ui_faq_a_track' => array( 'When your order is dispatched, you will receive an email with the tracking number. You can also check its status in My account → Orders. If tracking has not updated within 48–72 hours, contact support and provide your order number.', 'Sobald Ihre Bestellung versandt wird, erhalten Sie eine E-Mail mit der Sendungsnummer. Den Status finden Sie auch unter Mein Konto → Bestellungen. Wenn sich die Sendungsverfolgung innerhalb von 48–72 Stunden nicht aktualisiert, kontaktieren Sie den Support mit Ihrer Bestellnummer.', 'Lorsque votre commande est expédiée, vous recevez un e-mail avec le numéro de suivi. Vous pouvez également consulter son statut dans Mon compte → Commandes. Si le suivi ne se met pas à jour sous 48 à 72 h, contactez le support avec votre numéro de commande.', 'Quando il tuo ordine viene spedito, riceverai un’e-mail con il numero di tracking. Puoi anche controllarne lo stato in Il mio account → Ordini. Se il tracking non si aggiorna entro 48–72 ore, contatta l’assistenza indicando il numero d’ordine.', 'Quando a sua encomenda for expedida, receberá um e-mail com o número de rastreio. Também pode consultar o estado em A minha conta → Encomendas. Se o rastreio não for atualizado em 48–72 h, contacte o apoio com o número da encomenda.' ),
		'doroshopping_ui_faq_q_modify' => array( 'Can I change or cancel an order?', 'Kann ich eine Bestellung ändern oder stornieren?', 'Puis-je modifier ou annuler une commande ?', 'Posso modificare o annullare un ordine?', 'Posso alterar ou cancelar uma encomenda?' ),
		'doroshopping_ui_faq_a_modify' => array( 'If your order has not yet been processed or dispatched, we can try to change or cancel it. Contact the Help centre as soon as possible with your order number. Once it is in transit, you can only arrange a return after receiving it.', 'Wenn Ihre Bestellung noch nicht bearbeitet oder versandt wurde, können wir versuchen, sie zu ändern oder zu stornieren. Wenden Sie sich schnellstmöglich mit Ihrer Bestellnummer an das Hilfe-Center. Sobald sie unterwegs ist, können Sie eine Rückgabe erst nach Erhalt veranlassen.', 'Si votre commande n’a pas encore été traitée ni expédiée, nous pouvons tenter de la modifier ou de l’annuler. Contactez le Centre d’aide au plus vite avec votre numéro de commande. Une fois en transit, vous pourrez seulement organiser un retour après réception.', 'Se l’ordine non è ancora stato elaborato o spedito, possiamo provare a modificarlo o annullarlo. Contatta al più presto il Centro assistenza con il numero d’ordine. Una volta in transito, potrai gestire il reso solo dopo averlo ricevuto.', 'Se a sua encomenda ainda não tiver sido processada ou expedida, podemos tentar alterá-la ou cancelá-la. Contacte o Centro de ajuda o mais depressa possível com o número da encomenda. Depois de estar em trânsito, só poderá tratar da devolução após a receção.' ),
		'doroshopping_ui_faq_q_email' => array( 'I have not received the confirmation email', 'Ich habe die Bestätigungs-E-Mail nicht erhalten', 'Je n’ai pas reçu l’e-mail de confirmation', 'Non ho ricevuto l’e-mail di conferma', 'Não recebi o e-mail de confirmação' ),
		'doroshopping_ui_faq_a_email' => array( 'Check your spam or promotions folder. Confirm that your account email is correct in My account → Details. If payment was completed, the order should appear in your history even if the email is delayed.', 'Prüfen Sie Ihren Spam- oder Werbeordner. Stellen Sie unter Mein Konto → Details sicher, dass Ihre E-Mail-Adresse korrekt ist. Wenn die Zahlung abgeschlossen wurde, sollte die Bestellung in Ihrem Verlauf erscheinen, auch wenn die E-Mail verspätet eintrifft.', 'Vérifiez vos dossiers spam ou promotions. Confirmez que l’e-mail de votre compte est correct dans Mon compte → Détails. Si le paiement a été effectué, la commande devrait apparaître dans votre historique même si l’e-mail est retardé.', 'Controlla la cartella spam o promozioni. Verifica che l’e-mail dell’account sia corretta in Il mio account → Dettagli. Se il pagamento è stato completato, l’ordine dovrebbe apparire nello storico anche se l’e-mail è in ritardo.', 'Verifique as pastas de spam ou promoções. Confirme que o e-mail da sua conta está correto em A minha conta → Detalhes. Se o pagamento foi concluído, a encomenda deverá surgir no histórico mesmo que o e-mail esteja atrasado.' ),
		'doroshopping_ui_faq_q_methods' => array( 'Which payment methods do you accept?', 'Welche Zahlungsmethoden akzeptieren Sie?', 'Quels moyens de paiement acceptez-vous ?', 'Quali metodi di pagamento accettate?', 'Que métodos de pagamento aceitam?' ),
		'doroshopping_ui_faq_a_methods' => array( 'We accept the payment gateways available at checkout: cards, local European methods such as Klarna where applicable, and other options enabled for your country and currency. Payment is processed securely; we do not store your full card number.', 'Wir akzeptieren die an der Kasse verfügbaren Zahlungsmethoden: Karten, lokale europäische Methoden wie Klarna, sofern verfügbar, sowie weitere für Ihr Land und Ihre Währung aktivierte Optionen. Die Zahlung wird sicher verarbeitet; wir speichern nicht Ihre vollständige Kartennummer.', 'Nous acceptons les moyens de paiement disponibles au checkout : cartes, moyens locaux européens comme Klarna selon les cas, et autres options activées pour votre pays et votre devise. Le paiement est traité de manière sécurisée ; nous ne conservons pas le numéro complet de votre carte.', 'Accettiamo i metodi disponibili al checkout: carte, soluzioni europee locali come Klarna quando applicabili e altre opzioni abilitate per il tuo Paese e la tua valuta. Il pagamento è elaborato in modo sicuro; non conserviamo il numero completo della carta.', 'Aceitamos os métodos de pagamento disponíveis no checkout: cartões, métodos locais europeus como Klarna quando aplicável e outras opções ativadas para o seu país e moeda. O pagamento é processado de forma segura; não guardamos o número completo do cartão.' ),
		'doroshopping_ui_faq_q_charge' => array( 'Why have I been charged or had an amount authorised?', 'Warum wurde mir ein Betrag berechnet oder autorisiert?', 'Pourquoi un montant a-t-il été débité ou autorisé ?', 'Perché mi è stato addebitato o autorizzato un importo?', 'Porque foi cobrado ou autorizado um montante?' ),
		'doroshopping_ui_faq_a_charge' => array( 'When paying by card, a pre-authorisation or charge at order confirmation is normal. If you cancel in time or the order fails, the amount is released according to your bank’s timeframes, which may take several business days.', 'Bei Kartenzahlung ist eine Vorautorisierung oder Belastung bei Bestellbestätigung üblich. Wenn Sie rechtzeitig stornieren oder die Bestellung fehlschlägt, wird der Betrag nach den Fristen Ihrer Bank freigegeben, was mehrere Werktage dauern kann.', 'Lors d’un paiement par carte, une préautorisation ou un débit à la confirmation de commande est habituel. Si vous annulez à temps ou si la commande échoue, le montant est libéré selon les délais de votre banque, ce qui peut prendre plusieurs jours ouvrés.', 'Quando paghi con carta, è normale una preautorizzazione o un addebito alla conferma dell’ordine. Se annulli in tempo o l’ordine non va a buon fine, l’importo viene sbloccato secondo i tempi della tua banca, che possono richiedere vari giorni lavorativi.', 'Ao pagar com cartão, é normal haver uma pré-autorização ou cobrança na confirmação da encomenda. Se cancelar a tempo ou se a encomenda falhar, o montante é libertado de acordo com os prazos do seu banco, o que pode demorar vários dias úteis.' ),
		'doroshopping_ui_faq_q_coupon' => array( 'Can I use a discount coupon?', 'Kann ich einen Rabattgutschein verwenden?', 'Puis-je utiliser un coupon de réduction ?', 'Posso usare un coupon sconto?', 'Posso usar um cupão de desconto?' ),
		'doroshopping_ui_faq_a_coupon' => array( 'Yes. Enter the code on the Coupons page, in the cart or at checkout. The coupon must be active, not expired and meet its conditions, such as minimum spend, eligible products or single use.', 'Ja. Geben Sie den Code auf der Gutscheinseite, im Warenkorb oder an der Kasse ein. Der Gutschein muss aktiv, nicht abgelaufen sein und seine Bedingungen erfüllen, etwa Mindestbestellwert, berechtigte Produkte oder einmalige Verwendung.', 'Oui. Saisissez le code sur la page Coupons, dans le panier ou au checkout. Le coupon doit être actif, non expiré et respecter ses conditions : montant minimum, produits éligibles ou usage unique.', 'Sì. Inserisci il codice nella pagina Coupon, nel carrello o al checkout. Il coupon deve essere attivo, non scaduto e rispettare le condizioni, come importo minimo, prodotti idonei o utilizzo unico.', 'Sim. Introduza o código na página Cupões, no carrinho ou no checkout. O cupão deve estar ativo, não expirado e cumprir as condições, como valor mínimo, produtos elegíveis ou utilização única.' ),
		'doroshopping_ui_faq_q_time' => array( 'How long does shipping take?', 'Wie lange dauert der Versand?', 'Combien de temps prend la livraison ?', 'Quanto tempo richiede la spedizione?', 'Quanto tempo demora o envio?' ),
		'doroshopping_ui_faq_a_time' => array( 'Delivery times depend on the destination, product and carrier. In Spain and the EU they usually range from a few days to a couple of weeks after dispatch. Product pages and the Shipping page show indicative estimates.', 'Die Lieferzeiten hängen von Zielort, Produkt und Versanddienstleister ab. In Spanien und der EU reichen sie nach dem Versand meist von einigen Tagen bis zu ein paar Wochen. Produktseiten und die Versandseite zeigen voraussichtliche Lieferzeiten.', 'Les délais dépendent de la destination, du produit et du transporteur. En Espagne et dans l’UE, ils vont généralement de quelques jours à deux semaines après l’expédition. Les fiches produit et la page Livraison affichent des estimations indicatives.', 'I tempi dipendono dalla destinazione, dal prodotto e dal corriere. In Spagna e nell’UE variano di solito da alcuni giorni a un paio di settimane dopo la spedizione. Le pagine dei prodotti e la pagina Spedizioni mostrano stime indicative.', 'Os prazos dependem do destino, do produto e da transportadora. Em Espanha e na UE, normalmente variam de alguns dias a algumas semanas após a expedição. As páginas de produto e a página Envios mostram estimativas indicativas.' ),
		'doroshopping_ui_faq_q_costs' => array( 'Are there shipping costs or customs charges?', 'Gibt es Versandkosten oder Zollgebühren?', 'Y a-t-il des frais de livraison ou de douane ?', 'Ci sono costi di spedizione o doganali?', 'Existem custos de envio ou encargos aduaneiros?' ),
		'doroshopping_ui_faq_a_costs' => array( 'Shipping costs are calculated in the cart based on address and weight/volume. For international deliveries outside the EU, import duties or VAT may be charged to the recipient under local regulations.', 'Die Versandkosten werden im Warenkorb nach Adresse und Gewicht/Volumen berechnet. Bei internationalen Lieferungen außerhalb der EU können gemäß den örtlichen Vorschriften Einfuhrzölle oder Mehrwertsteuer zulasten des Empfängers anfallen.', 'Les frais de livraison sont calculés dans le panier selon l’adresse et le poids/volume. Pour les livraisons internationales hors UE, des droits de douane ou une TVA à l’importation peuvent être à la charge du destinataire selon la réglementation locale.', 'I costi di spedizione sono calcolati nel carrello in base all’indirizzo e al peso/volume. Per le spedizioni internazionali fuori dall’UE, dazi o IVA all’importazione possono essere a carico del destinatario secondo le norme locali.', 'Os custos de envio são calculados no carrinho com base na morada e no peso/volume. Para envios internacionais fora da UE, podem aplicar-se direitos aduaneiros ou IVA de importação a cargo do destinatário, conforme a legislação local.' ),
		'doroshopping_ui_faq_q_missing' => array( 'My parcel is marked as delivered but I have not received it', 'Mein Paket wird als zugestellt angezeigt, aber ich habe es nicht erhalten', 'Mon colis est indiqué comme livré mais je ne l’ai pas reçu', 'Il pacco risulta consegnato ma non l’ho ricevuto', 'A encomenda aparece como entregue, mas não a recebi' ),
		'doroshopping_ui_faq_a_missing' => array( 'Check with neighbours, reception or collection points. If it does not appear within 24–48 hours, contact support with the tracking details and photos of the incident; we will open a claim with the carrier.', 'Fragen Sie bei Nachbarn, dem Empfang oder Abholstellen nach. Wenn das Paket innerhalb von 24–48 Stunden nicht auftaucht, kontaktieren Sie den Support mit den Trackingdaten und Fotos des Vorfalls; wir eröffnen eine Reklamation beim Versanddienstleister.', 'Vérifiez auprès des voisins, du gardien ou des points de retrait. S’il ne réapparaît pas sous 24 à 48 h, contactez le support avec le suivi et des photos de l’incident ; nous ouvrirons une réclamation auprès du transporteur.', 'Verifica con vicini, portineria o punti di ritiro. Se non compare entro 24–48 ore, contatta l’assistenza con il tracking e foto del problema; apriremo un reclamo con il corriere.', 'Verifique junto de vizinhos, portaria ou pontos de recolha. Se não aparecer em 24–48 h, contacte o apoio com os dados de rastreio e fotos da ocorrência; abriremos uma reclamação junto da transportadora.' ),
		'doroshopping_ui_faq_q_how' => array( 'How do I request a return?', 'Wie beantrage ich eine Rückgabe?', 'Comment demander un retour ?', 'Come richiedo un reso?', 'Como solicito uma devolução?' ),
		'doroshopping_ui_faq_a_how' => array( 'Within the legal withdrawal period, usually 14 days from receipt in the EU, request a return through the Help centre or consult the Returns policy. The product must be in good condition and, where possible, in its packaging.', 'Beantragen Sie innerhalb der gesetzlichen Widerrufsfrist, in der EU normalerweise 14 Tage nach Erhalt, eine Rückgabe über das Hilfe-Center oder lesen Sie die Rückgaberichtlinie. Das Produkt muss in gutem Zustand und möglichst in seiner Verpackung sein.', 'Pendant le délai légal de rétractation, généralement 14 jours après réception dans l’UE, demandez un retour via le Centre d’aide ou consultez la Politique de retours. Le produit doit être en bon état et, si possible, dans son emballage.', 'Entro il periodo legale di recesso, normalmente 14 giorni dalla ricezione nell’UE, richiedi un reso tramite il Centro assistenza o consulta la Politica dei resi. Il prodotto deve essere in buone condizioni e, quando possibile, nell’imballaggio.', 'Durante o prazo legal de livre resolução, normalmente 14 dias após a receção na UE, solicite a devolução através do Centro de ajuda ou consulte a Política de devoluções. O produto deve estar em bom estado e, quando possível, na embalagem.' ),
		'doroshopping_ui_faq_q_refund' => array( 'When will I receive my refund?', 'Wann erhalte ich meine Erstattung?', 'Quand recevrai-je mon remboursement ?', 'Quando riceverò il rimborso?', 'Quando receberei o reembolso?' ),
		'doroshopping_ui_faq_a_refund' => array( 'Once we receive and inspect the return, we process the refund to the original payment method. The credit to your bank account may take several business days depending on the bank or payment gateway.', 'Sobald wir die Rückgabe erhalten und geprüft haben, bearbeiten wir die Erstattung über die ursprüngliche Zahlungsmethode. Die Gutschrift auf Ihrem Bankkonto kann je nach Bank oder Zahlungsanbieter mehrere Werktage dauern.', 'Après réception et vérification du retour, nous procédons au remboursement sur le moyen de paiement d’origine. Le crédit sur votre compte bancaire peut prendre plusieurs jours ouvrés selon la banque ou le prestataire de paiement.', 'Dopo aver ricevuto e verificato il reso, elaboriamo il rimborso sul metodo di pagamento originale. L’accredito sul conto bancario può richiedere vari giorni lavorativi secondo la banca o il gestore dei pagamenti.', 'Após recebermos e verificarmos a devolução, processamos o reembolso para o método de pagamento original. O crédito na conta bancária pode demorar vários dias úteis, dependendo do banco ou do prestador de pagamento.' ),
		'doroshopping_ui_faq_q_damaged' => array( 'The product arrived damaged or incorrect', 'Das Produkt ist beschädigt oder falsch angekommen', 'Le produit est arrivé endommagé ou incorrect', 'Il prodotto è arrivato danneggiato o errato', 'O produto chegou danificado ou incorreto' ),
		'doroshopping_ui_faq_a_damaged' => array( 'Contact us within the first 48 hours with your order number, photos of the damage or packaging and a description. We will arrange a replacement, refund or equivalent solution according to the case.', 'Kontaktieren Sie uns innerhalb der ersten 48 Stunden mit Ihrer Bestellnummer, Fotos von Schäden oder Verpackung und einer Beschreibung. Je nach Fall veranlassen wir Ersatz, Erstattung oder eine gleichwertige Lösung.', 'Contactez-nous dans les 48 premières heures avec votre numéro de commande, des photos des dommages ou de l’emballage et une description. Nous organiserons un remplacement, un remboursement ou une solution équivalente selon le cas.', 'Contattaci entro le prime 48 ore con il numero d’ordine, foto del danno o dell’imballaggio e una descrizione. Organizzeremo una sostituzione, un rimborso o una soluzione equivalente a seconda del caso.', 'Contacte-nos nas primeiras 48 h com o número da encomenda, fotos dos danos ou da embalagem e uma descrição. Trataremos de uma substituição, reembolso ou solução equivalente, conforme o caso.' ),
		'doroshopping_ui_faq_q_mismatch' => array( 'The description does not match the product', 'Die Beschreibung stimmt nicht mit dem Produkt überein', 'La description ne correspond pas au produit', 'La descrizione non corrisponde al prodotto', 'A descrição não corresponde ao produto' ),
		'doroshopping_ui_faq_a_mismatch' => array( 'Product pages are based on supplier information. If there is a material discrepancy, send us photos and your order number so we can review it and offer a solution.', 'Die Produktseiten basieren auf Angaben des Lieferanten. Wenn eine wesentliche Abweichung vorliegt, senden Sie uns Fotos und Ihre Bestellnummer, damit wir dies prüfen und eine Lösung anbieten können.', 'Les fiches produit reposent sur les informations du fournisseur. En cas d’écart important, envoyez-nous des photos et votre numéro de commande afin que nous puissions l’examiner et vous proposer une solution.', 'Le pagine dei prodotti si basano sulle informazioni del fornitore. Se c’è una discrepanza rilevante, inviaci foto e numero d’ordine per permetterci di verificarla e offrirti una soluzione.', 'As páginas de produto baseiam-se nas informações do fornecedor. Se existir uma discrepância relevante, envie-nos fotos e o número da encomenda para analisarmos e lhe oferecermos uma solução.' ),
		'doroshopping_ui_faq_q_warranty' => array( 'Do products have a warranty?', 'Haben Produkte eine Garantie?', 'Les produits sont-ils garantis ?', 'I prodotti hanno una garanzia?', 'Os produtos têm garantia?' ),
		'doroshopping_ui_faq_a_warranty' => array( 'EU legal conformity warranty rights apply. Keep your invoice or order confirmation. For operational faults, contact support with a description of the defect and supporting evidence.', 'Es gelten die gesetzlichen Gewährleistungsrechte der EU. Bewahren Sie Ihre Rechnung oder Bestellbestätigung auf. Bei Funktionsstörungen kontaktieren Sie den Support mit einer Beschreibung des Mangels und entsprechenden Nachweisen.', 'Les droits à la garantie légale de conformité de l’UE s’appliquent. Conservez votre facture ou confirmation de commande. En cas de dysfonctionnement, contactez le support en indiquant le défaut et les éléments justificatifs.', 'Si applicano i diritti di garanzia legale di conformità dell’UE. Conserva la fattura o la conferma dell’ordine. Per difetti di funzionamento, contatta l’assistenza indicando il difetto e le prove.', 'Aplicam-se os direitos da garantia legal de conformidade da UE. Guarde a fatura ou confirmação da encomenda. Em caso de avarias, contacte o apoio indicando o defeito e os respetivos comprovativos.' ),
		'doroshopping_ui_faq_cta_title' => array( 'Still need help?', 'Benötigen Sie weiterhin Hilfe?', 'Vous avez encore besoin d’aide ?', 'Hai ancora bisogno di aiuto?', 'Ainda precisa de ajuda?' ),
		'doroshopping_ui_faq_cta_text' => array( 'Our customer service team is ready to help with your specific case.', 'Unser Kundenservice-Team hilft Ihnen gern bei Ihrem konkreten Anliegen.', 'Notre équipe de service client est prête à vous aider pour votre situation.', 'Il nostro servizio clienti è pronto ad aiutarti con il tuo caso specifico.', 'A nossa equipa de apoio ao cliente está pronta para ajudar no seu caso específico.' ),
		'doroshopping_ui_faq_cta_btn' => array( 'Go to Help centre', 'Zum Hilfe-Center', 'Aller au Centre d’aide', 'Vai al Centro assistenza', 'Ir para o Centro de ajuda' ),

		// Payments, buyer protection and wishlist.
		'doroshopping_ui_paypage_eyebrow' => array( 'Secure shopping', 'Sicher einkaufen', 'Achats sécurisés', 'Acquisti sicuri', 'Compra segura' ),
		'doroshopping_ui_paypage_title' => array( 'Payment methods', 'Zahlungsmethoden', 'Moyens de paiement', 'Metodi di pagamento', 'Métodos de pagamento' ),
		'doroshopping_ui_paypage_lead' => array( 'Pay using the methods available at checkout. All transactions are processed with encryption and certified payment gateways.', 'Bezahlen Sie mit den an der Kasse verfügbaren Methoden. Alle Transaktionen werden verschlüsselt über zertifizierte Zahlungsanbieter abgewickelt.', 'Payez avec les moyens disponibles au checkout. Toutes les transactions sont traitées avec chiffrement et par des prestataires certifiés.', 'Paga con i metodi disponibili al checkout. Tutte le transazioni sono elaborate con crittografia e provider certificati.', 'Pague com os métodos disponíveis no checkout. Todas as transações são processadas com encriptação e prestadores certificados.' ),
		'doroshopping_ui_paypage_methods_title' => array( 'Accepted payment methods', 'Akzeptierte Zahlungsmethoden', 'Moyens de paiement acceptés', 'Metodi di pagamento accettati', 'Métodos de pagamento aceites' ),
		'doroshopping_ui_paypage_methods_intro' => array( 'The options shown at checkout may vary depending on your country, currency and the store configuration.', 'Die an der Kasse angezeigten Optionen können je nach Land, Währung und Shop-Konfiguration variieren.', 'Les options affichées au checkout peuvent varier selon votre pays, votre devise et la configuration de la boutique.', 'Le opzioni visibili al checkout possono variare in base al Paese, alla valuta e alla configurazione del negozio.', 'As opções apresentadas no checkout podem variar conforme o seu país, moeda e a configuração da loja.' ),
		'doroshopping_ui_paypage_card_title' => array( 'Credit / debit card', 'Kredit- / Debitkarte', 'Carte de crédit / débit', 'Carta di credito / debito', 'Cartão de crédito / débito' ),
		'doroshopping_ui_paypage_card_text' => array( 'Visa, Mastercard and other cards supported by the gateway. The charge or pre-authorisation is made when you confirm the order.', 'Visa, Mastercard und andere vom Zahlungsanbieter unterstützte Karten. Die Belastung oder Vorautorisierung erfolgt bei Bestellbestätigung.', 'Visa, Mastercard et autres cartes prises en charge par le prestataire. Le débit ou la préautorisation a lieu à la confirmation de la commande.', 'Visa, Mastercard e altre carte supportate dal provider. L’addebito o la preautorizzazione avviene alla conferma dell’ordine.', 'Visa, Mastercard e outros cartões suportados pelo prestador. A cobrança ou pré-autorização é efetuada quando confirma a encomenda.' ),
		'doroshopping_ui_paypage_local_title' => array( 'Deferred / local payment', 'Später zahlen / lokale Zahlung', 'Paiement différé / local', 'Pagamento differito / locale', 'Pagamento diferido / local' ),
		'doroshopping_ui_paypage_local_text' => array( 'Methods such as Klarna or other local European solutions when enabled in your country.', 'Methoden wie Klarna oder andere lokale europäische Lösungen, sofern sie in Ihrem Land aktiviert sind.', 'Des moyens tels que Klarna ou d’autres solutions locales européennes lorsqu’ils sont activés dans votre pays.', 'Metodi come Klarna o altre soluzioni europee locali quando abilitati nel tuo Paese.', 'Métodos como Klarna ou outras soluções locais europeias quando ativados no seu país.' ),
		'doroshopping_ui_paypage_wallet_title' => array( 'Wallets and others', 'Wallets und weitere Optionen', 'Portefeuilles électroniques et autres', 'Wallet e altri', 'Carteiras digitais e outros' ),
		'doroshopping_ui_paypage_wallet_text' => array( 'If enabled, such as PayPal or other wallets, they will appear automatically on the payment page.', 'Wenn sie aktiviert sind, etwa PayPal oder andere Wallets, werden sie automatisch auf der Zahlungsseite angezeigt.', 'S’ils sont activés, comme PayPal ou d’autres portefeuilles électroniques, ils apparaîtront automatiquement sur la page de paiement.', 'Se attivati, ad esempio PayPal o altri wallet, appariranno automaticamente nella pagina di pagamento.', 'Se estiverem ativados, como o PayPal ou outras carteiras digitais, surgirão automaticamente na página de pagamento.' ),
		'doroshopping_ui_paypage_img_alt' => array( 'Accepted payment methods', 'Akzeptierte Zahlungsmethoden', 'Moyens de paiement acceptés', 'Metodi di pagamento accettati', 'Métodos de pagamento aceites' ),
		'doroshopping_ui_paypage_secure_title' => array( 'Payment security', 'Zahlungssicherheit', 'Sécurité des paiements', 'Sicurezza dei pagamenti', 'Segurança do pagamento' ),
		'doroshopping_ui_paypage_secure_1' => array( 'HTTPS connection throughout the store.', 'HTTPS-Verbindung im gesamten Shop.', 'Connexion HTTPS sur toute la boutique.', 'Connessione HTTPS in tutto il negozio.', 'Ligação HTTPS em toda a loja.' ),
		'doroshopping_ui_paypage_secure_2' => array( 'Card data is handled by the payment gateway; we do not store the full number.', 'Kartendaten werden vom Zahlungsanbieter verarbeitet; wir speichern nicht die vollständige Nummer.', 'Les données de carte sont gérées par le prestataire de paiement ; nous ne conservons pas le numéro complet.', 'I dati della carta sono gestiti dal provider; non conserviamo il numero completo.', 'Os dados do cartão são geridos pelo prestador de pagamento; não guardamos o número completo.' ),
		'doroshopping_ui_paypage_secure_3' => array( 'Email confirmation after successful payment.', 'E-Mail-Bestätigung nach erfolgreicher Zahlung.', 'Confirmation par e-mail après un paiement réussi.', 'Conferma via e-mail dopo un pagamento riuscito.', 'Confirmação por e-mail após um pagamento bem-sucedido.' ),
		'doroshopping_ui_paypage_protect_btn' => array( 'Buyer protection', 'Käuferschutz', 'Protection de l’acheteur', 'Protezione acquirente', 'Proteção do comprador' ),
		'doroshopping_ui_paypage_tips_title' => array( 'Useful tips', 'Nützliche Hinweise', 'Conseils utiles', 'Consigli utili', 'Conselhos úteis' ),
		'doroshopping_ui_paypage_tips_1' => array( 'Check the amount and currency before confirming.', 'Prüfen Sie Betrag und Währung vor der Bestätigung.', 'Vérifiez le montant et la devise avant de confirmer.', 'Controlla l’importo e la valuta prima di confermare.', 'Confirme o montante e a moeda antes de validar.' ),
		'doroshopping_ui_paypage_tips_2' => array( 'If you see a pending pre-authorisation, it is usually released if the order is not completed.', 'Wenn Sie eine ausstehende Vorautorisierung sehen, wird sie normalerweise freigegeben, falls die Bestellung nicht abgeschlossen wird.', 'Si vous voyez une préautorisation en attente, elle est généralement libérée si la commande n’est pas finalisée.', 'Se vedi una preautorizzazione in sospeso, di solito viene sbloccata se l’ordine non viene completato.', 'Se vir uma pré-autorização pendente, normalmente será libertada se a encomenda não for concluída.' ),
		'doroshopping_ui_paypage_tips_3' => array( 'Keep your order number for any billing query.', 'Bewahren Sie Ihre Bestellnummer für Rückfragen zur Abrechnung auf.', 'Conservez votre numéro de commande pour toute question de facturation.', 'Conserva il numero d’ordine per qualsiasi richiesta di fatturazione.', 'Guarde o número da encomenda para qualquer questão de faturação.' ),
		'doroshopping_ui_paypage_help_btn' => array( 'Get help with a payment', 'Hilfe zu einer Zahlung', 'Obtenir de l’aide pour un paiement', 'Aiuto per un pagamento', 'Ajuda com um pagamento' ),
		'doroshopping_ui_paypage_cta_title' => array( 'Ready to shop?', 'Bereit zum Einkaufen?', 'Prêt à acheter ?', 'Pronto per acquistare?', 'Pronto para comprar?' ),
		'doroshopping_ui_paypage_cta_text' => array( 'Choose your products and complete payment through secure checkout.', 'Wählen Sie Ihre Produkte und schließen Sie die Zahlung über einen sicheren Checkout ab.', 'Choisissez vos produits et finalisez le paiement via un checkout sécurisé.', 'Scegli i tuoi prodotti e completa il pagamento con un checkout sicuro.', 'Escolha os seus produtos e conclua o pagamento num checkout seguro.' ),
		'doroshopping_ui_paypage_cta_btn' => array( 'Go to checkout', 'Zur Kasse', 'Passer au paiement', 'Vai al checkout', 'Ir para o checkout' ),
		'doroshopping_ui_protect_eyebrow' => array( 'Trust', 'Vertrauen', 'Confiance', 'Fiducia', 'Confiança' ),
		'doroshopping_ui_protect_title' => array( 'Security and buyer protection', 'Sicherheit und Käuferschutz', 'Sécurité et protection de l’acheteur', 'Sicurezza e protezione acquirenti', 'Segurança e proteção do comprador' ),
		'doroshopping_ui_protect_lead' => array( 'At %s, we protect your purchase with secure payments, order tracking and support when problems arise.', 'Bei %s schützen wir Ihren Einkauf mit sicheren Zahlungen, Sendungsverfolgung und Unterstützung bei Problemen.', 'Chez %s, nous protégeons vos achats avec des paiements sécurisés, le suivi des commandes et une assistance en cas de problème.', 'In %s proteggiamo il tuo acquisto con pagamenti sicuri, tracciamento dell’ordine e assistenza in caso di problemi.', 'Na %s protegemos a sua compra com pagamentos seguros, rastreio da encomenda e apoio em caso de problemas.' ),
		'doroshopping_ui_protect_pay_title' => array( 'Secure payments', 'Sichere Zahlungen', 'Paiements sécurisés', 'Pagamenti sicuri', 'Pagamentos seguros' ),
		'doroshopping_ui_protect_pay_text' => array( 'SSL/TLS-encrypted transactions through certified gateways. We do not store your full card number.', 'SSL/TLS-verschlüsselte Transaktionen über zertifizierte Zahlungsanbieter. Wir speichern nicht Ihre vollständige Kartennummer.', 'Transactions chiffrées SSL/TLS via des prestataires certifiés. Nous ne conservons pas le numéro complet de votre carte.', 'Transazioni crittografate SSL/TLS tramite provider certificati. Non conserviamo il numero completo della carta.', 'Transações encriptadas com SSL/TLS através de prestadores certificados. Não guardamos o número completo do cartão.' ),
		'doroshopping_ui_protect_track_title' => array( 'Order tracking', 'Sendungsverfolgung', 'Suivi de commande', 'Tracciamento dell’ordine', 'Rastreio da encomenda' ),
		'doroshopping_ui_protect_track_text' => array( 'Email confirmation and access to delivery status from your account when tracking is available.', 'E-Mail-Bestätigung und Zugriff auf den Lieferstatus über Ihr Konto, sobald Tracking verfügbar ist.', 'Confirmation par e-mail et accès au statut de livraison depuis votre compte lorsque le suivi est disponible.', 'Conferma via e-mail e accesso allo stato della consegna dal tuo account quando il tracking è disponibile.', 'Confirmação por e-mail e acesso ao estado da entrega através da sua conta quando o rastreio estiver disponível.' ),
		'doroshopping_ui_protect_support_title' => array( 'Support when problems arise', 'Hilfe bei Problemen', 'Assistance en cas de problème', 'Assistenza in caso di problemi', 'Apoio em caso de problemas' ),
		'doroshopping_ui_protect_support_text' => array( 'If there is a delivery, product or billing problem, our team can help through the Help centre.', 'Bei Problemen mit Lieferung, Produkt oder Zahlung hilft Ihnen unser Team über das Hilfe-Center.', 'En cas de problème de livraison, de produit ou de paiement, notre équipe peut vous aider via le Centre d’aide.', 'In caso di problemi con consegna, prodotto o addebito, il nostro team può aiutarti dal Centro assistenza.', 'Se houver um problema de entrega, produto ou cobrança, a nossa equipa poderá ajudar através do Centro de ajuda.' ),
		'doroshopping_ui_protect_rights_title' => array( 'Your consumer rights', 'Ihre Verbraucherrechte', 'Vos droits de consommateur', 'I tuoi diritti di consumatore', 'Os seus direitos enquanto consumidor' ),
		'doroshopping_ui_protect_rights_1' => array( 'Right of withdrawal under EU rules; see the Returns policy.', 'Widerrufsrecht nach EU-Vorschriften; siehe Rückgaberichtlinie.', 'Droit de rétractation conformément aux règles de l’UE ; consultez la Politique de retours.', 'Diritto di recesso secondo la normativa UE; consulta la Politica dei resi.', 'Direito de livre resolução ao abrigo das regras da UE; consulte a Política de devoluções.' ),
		'doroshopping_ui_protect_rights_2' => array( 'Legal conformity warranty for defective products.', 'Gesetzliche Gewährleistung für mangelhafte Produkte.', 'Garantie légale de conformité pour les produits défectueux.', 'Garanzia legale di conformità per prodotti difettosi.', 'Garantia legal de conformidade aplicável a produtos defeituosos.' ),
		'doroshopping_ui_protect_rights_3' => array( 'Clear information about prices, shipping and terms before payment.', 'Klare Informationen zu Preisen, Versand und Bedingungen vor der Zahlung.', 'Informations claires sur les prix, la livraison et les conditions avant paiement.', 'Informazioni chiare su prezzi, spedizione e condizioni prima del pagamento.', 'Informação clara sobre preços, envio e condições antes do pagamento.' ),
		'doroshopping_ui_protect_returns_btn' => array( 'View returns', 'Rückgaben ansehen', 'Voir les retours', 'Vedi i resi', 'Ver devoluções' ),
		'doroshopping_ui_protect_tips_title' => array( 'Practical tips', 'Praktische Tipps', 'Conseils pratiques', 'Consigli pratici', 'Conselhos práticos' ),
		'doroshopping_ui_protect_tips_1' => array( 'Check the delivery address before confirming.', 'Prüfen Sie die Lieferadresse vor der Bestätigung.', 'Vérifiez l’adresse de livraison avant de confirmer.', 'Controlla l’indirizzo di consegna prima di confermare.', 'Confirme a morada de entrega antes de validar.' ),
		'doroshopping_ui_protect_tips_2' => array( 'Keep the confirmation email and order number.', 'Bewahren Sie Bestätigungs-E-Mail und Bestellnummer auf.', 'Conservez l’e-mail de confirmation et le numéro de commande.', 'Conserva l’e-mail di conferma e il numero d’ordine.', 'Guarde o e-mail de confirmação e o número da encomenda.' ),
		'doroshopping_ui_protect_tips_3' => array( 'Contact us if you notice an unrecognised charge.', 'Kontaktieren Sie uns, wenn Sie eine nicht erkannte Belastung feststellen.', 'Contactez-nous si vous constatez un débit non reconnu.', 'Contattaci se noti un addebito non riconosciuto.', 'Contacte-nos se detetar uma cobrança não reconhecida.' ),
		'doroshopping_ui_protect_tips_4' => array( 'Always use the HTTPS website and never share your credentials.', 'Nutzen Sie immer die HTTPS-Website und geben Sie Ihre Zugangsdaten niemals weiter.', 'Utilisez toujours le site en HTTPS et ne partagez jamais vos identifiants.', 'Usa sempre il sito HTTPS e non condividere mai le tue credenziali.', 'Utilize sempre o site em HTTPS e nunca partilhe as suas credenciais.' ),
		'doroshopping_ui_protect_privacy_btn' => array( 'Privacy policy', 'Datenschutzerklärung', 'Politique de confidentialité', 'Informativa sulla privacy', 'Política de privacidade' ),
		'doroshopping_ui_protect_cta_title' => array( 'Need help with a purchase?', 'Benötigen Sie Hilfe bei einem Einkauf?', 'Besoin d’aide pour un achat ?', 'Hai bisogno di aiuto con un acquisto?', 'Precisa de ajuda com uma compra?' ),
		'doroshopping_ui_protect_cta_text' => array( 'Write to us with your order number and we will reply as soon as possible.', 'Schreiben Sie uns mit Ihrer Bestellnummer, und wir antworten schnellstmöglich.', 'Écrivez-nous avec votre numéro de commande et nous vous répondrons dès que possible.', 'Scrivici indicando il numero d’ordine e ti risponderemo al più presto.', 'Escreva-nos com o número da encomenda e responderemos assim que possível.' ),
		'doroshopping_ui_protect_help_btn' => array( 'Help centre', 'Hilfe-Center', 'Centre d’aide', 'Centro assistenza', 'Centro de ajuda' ),
		'doroshopping_ui_protect_pay_btn' => array( 'Payment methods', 'Zahlungsmethoden', 'Moyens de paiement', 'Metodi di pagamento', 'Métodos de pagamento' ),
		'doroshopping_ui_wish_title' => array( 'Wishlist', 'Wunschliste', 'Liste de souhaits', 'Lista dei desideri', 'Lista de desejos' ),
		'doroshopping_ui_wish_subtitle' => array( 'Save your favourite products and come back to them whenever you want.', 'Speichern Sie Ihre Lieblingsprodukte und kehren Sie jederzeit zu ihnen zurück.', 'Enregistrez vos produits favoris et retrouvez-les quand vous le souhaitez.', 'Salva i tuoi prodotti preferiti e ritrovali quando vuoi.', 'Guarde os seus produtos favoritos e volte a eles quando quiser.' ),
		'doroshopping_ui_wish_login_notice' => array( 'Sign in to synchronise your wishlist across all your devices.', 'Melden Sie sich an, um Ihre Wunschliste auf all Ihren Geräten zu synchronisieren.', 'Connectez-vous pour synchroniser votre liste de souhaits sur tous vos appareils.', 'Accedi per sincronizzare la tua lista dei desideri su tutti i dispositivi.', 'Inicie sessão para sincronizar a sua lista de desejos em todos os dispositivos.' ),
		'doroshopping_ui_wish_login_cta' => array( 'Sign in / Register', 'Anmelden / Registrieren', 'Se connecter / S’inscrire', 'Accedi / Registrati', 'Iniciar sessão / Registar' ),
		'doroshopping_ui_wish_empty_title' => array( 'Your wishlist is empty', 'Ihre Wunschliste ist leer', 'Votre liste de souhaits est vide', 'La tua lista dei desideri è vuota', 'A sua lista de desejos está vazia' ),
		'doroshopping_ui_wish_empty_text' => array( 'Browse the shop and add products using the heart icon.', 'Entdecken Sie den Shop und fügen Sie Produkte über das Herzsymbol hinzu.', 'Parcourez la boutique et ajoutez des produits à l’aide de l’icône cœur.', 'Esplora il negozio e aggiungi prodotti usando l’icona a forma di cuore.', 'Explore a loja e adicione produtos através do ícone de coração.' ),
		'doroshopping_ui_wish_shop_cta' => array( 'Go to shop', 'Zum Shop', 'Aller à la boutique', 'Vai al negozio', 'Ir à loja' ),
	);

	$packs = array(
		'en' => array(),
		'de' => array(),
		'fr' => array(),
		'it' => array(),
		'pt' => array(),
	);

	foreach ( $entries as $key => $texts ) {
		$packs['en'][ $key ] = $texts[0];
		$packs['de'][ $key ] = $texts[1];
		$packs['fr'][ $key ] = $texts[2];
		$packs['it'][ $key ] = $texts[3];
		$packs['pt'][ $key ] = $texts[4];
	}

	return $packs;
}
